import { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { useApi } from '../../hooks/useApi';
import { useToast } from '../Common/ToastProvider';
import { ExternalProviderOperationStatus, type ExternalProviderOperation } from './ExternalProviderOperationStatus';
import { FolderTemplateBuilderModal, type DriveFolderTemplate } from '../Settings/GoogleDriveFolderTemplateBuilder';

type Template = DriveFolderTemplate;

export function GoogleDriveFolderTemplatesPanel({ projectId, projectName, canEdit }: { projectId: string; projectName: string; canEdit: boolean }) {
  const api = useApi(); const toast = useToast();
  const [templates, setTemplates] = useState<Template[]>([]); const [sources, setSources] = useState<Array<{ id: string; provider_source_id: string }>>([]);
  const [editing, setEditing] = useState<Template | 'new' | null>(null);
  const [operation, setOperation] = useState<ExternalProviderOperation | null>(null); const [busy, setBusy] = useState(false);
  const load = async () => { const [templateRows, sourceRows] = await Promise.all([api.getExternalFolderTemplates(), api.getProjectConnectedSources(projectId)]); setTemplates(Array.isArray(templateRows) ? templateRows as Template[] : []); setSources(Array.isArray(sourceRows) ? sourceRows as Array<{ id: string; provider_source_id: string }> : []); };
  useEffect(() => { void load().catch(() => undefined); }, [projectId]);
  const openEditor = (template: Template | 'new') => setEditing(template);
  const apply = async (template: Template) => { const destination = sources[0]?.provider_source_id; if (!destination) { toast.show('Connect a Google Drive folder to this project first.', { variant: 'error' }); return; } setBusy(true); try { const result = await api.createGoogleDriveProjectStructure(projectId, { template_id: template.id, destination_folder_id: destination, root_name: projectName, idempotency_key: `template:${projectId}:${template.id}:${Date.now()}` }) as { operation?: ExternalProviderOperation }; if (result.operation) setOperation(result.operation); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not apply folder template.', { variant: 'error' }); } finally { setBusy(false); } };
  const retry = async () => { if (!operation) return; setBusy(true); try { setOperation(await api.retryExternalProviderOperation(operation.id) as ExternalProviderOperation); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not retry failed folders.', { variant: 'error' }); } finally { setBusy(false); } };
  return <section className="mt-3 border-t border-[color:var(--ledger-border-subtle)] pt-3"><div className="flex items-center justify-between"><div><h3 className="text-xs font-semibold text-[var(--ledger-text-primary)]">Drive folder templates</h3><p className="mt-0.5 text-[11px] text-[var(--ledger-text-muted)]">Create a repeatable folder structure for this project.</p></div>{canEdit && <button type="button" onClick={() => openEditor('new')} className="inline-flex items-center gap-1 rounded-md border border-[color:var(--ledger-border-subtle)] px-2 py-1 text-[11px]"><Plus size={12} />New template</button>}</div>
    <div className="mt-2 space-y-1.5">{templates.map((template) => <div key={template.id} className="rounded-lg border border-[color:var(--ledger-border-subtle)] px-3 py-2"><div className="flex items-center gap-2"><span className="min-w-0 flex-1 truncate text-xs font-medium">{template.name}</span><span className="text-[11px] text-[var(--ledger-text-muted)]">{(template.structure?.folders || []).length} folders</span>{canEdit && <><button type="button" title="Preview" onClick={() => openEditor(template)} className="rounded p-1 hover:bg-[var(--ledger-surface-hover)]"><Pencil size={12} /></button><button type="button" title="Delete" onClick={() => { if (window.confirm(`Delete ${template.name}?`)) void api.deleteExternalFolderTemplate(template.id).then(load); }} className="rounded p-1 text-[var(--ledger-danger)] hover:bg-[var(--ledger-surface-hover)]"><Trash2 size={12} /></button><button type="button" disabled={busy} onClick={() => void apply(template)} className="rounded-md bg-[var(--ledger-accent)] px-2 py-1 text-[11px] text-white disabled:opacity-50">Apply</button></>}</div></div>)}</div>
    {operation && <div className="mt-3"><ExternalProviderOperationStatus operation={operation} onRetry={operation.status === 'failed' || operation.status === 'partially_completed' ? retry : undefined} /></div>}
    {editing && <FolderTemplateBuilderModal template={editing} onClose={() => setEditing(null)} busy={busy} onSave={async (payload) => { setBusy(true); try { if (editing === 'new') await api.createExternalFolderTemplate(payload); else await api.updateExternalFolderTemplate(editing.id, payload); await load(); setEditing(null); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not save template.', { variant: 'error' }); } finally { setBusy(false); } }} />}
  </section>;
}
