import { useEffect, useMemo, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { useApi } from '../../hooks/useApi';
import { useToast } from '../Common/ToastProvider';
import { ModalOverlay } from '../Common/ModalOverlay';
import { ExternalProviderOperationStatus, type ExternalProviderOperation } from './ExternalProviderOperationStatus';

type Folder = { name: string; children?: Folder[] };
type Template = { id: string; name: string; description?: string | null; structure?: { folders?: Folder[] } };

const defaultFolders = () => ({ folders: [{ name: '01 Planning' }, { name: '02 Working Files' }, { name: '03 Review' }, { name: '04 Final Deliverables' }] });

export function GoogleDriveFolderTemplatesPanel({ projectId, projectName, canEdit }: { projectId: string; projectName: string; canEdit: boolean }) {
  const api = useApi(); const toast = useToast();
  const [templates, setTemplates] = useState<Template[]>([]); const [sources, setSources] = useState<Array<{ id: string; provider_source_id: string }>>([]);
  const [editing, setEditing] = useState<Template | 'new' | null>(null); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [structure, setStructure] = useState(JSON.stringify(defaultFolders(), null, 2));
  const [operation, setOperation] = useState<ExternalProviderOperation | null>(null); const [busy, setBusy] = useState(false);
  const load = async () => { const [templateRows, sourceRows] = await Promise.all([api.getExternalFolderTemplates(), api.getProjectConnectedSources(projectId)]); setTemplates(Array.isArray(templateRows) ? templateRows as Template[] : []); setSources(Array.isArray(sourceRows) ? sourceRows as Array<{ id: string; provider_source_id: string }> : []); };
  useEffect(() => { void load().catch(() => undefined); }, [projectId]);
  const folders = useMemo(() => { try { const parsed = JSON.parse(structure); return Array.isArray(parsed.folders) ? parsed.folders as Folder[] : []; } catch { return []; } }, [structure]);
  const openEditor = (template: Template | 'new') => { setEditing(template); setName(template === 'new' ? '' : template.name); setDescription(template === 'new' ? '' : template.description || ''); setStructure(JSON.stringify(template === 'new' ? defaultFolders() : { folders: template.structure?.folders || [] }, null, 2)); };
  const save = async () => { let parsed: { folders: Folder[] }; try { parsed = JSON.parse(structure); if (!Array.isArray(parsed.folders)) throw new Error(); } catch { toast.show('Use valid folder structure JSON.', { variant: 'error' }); return; } setBusy(true); try { if (editing === 'new') await api.createExternalFolderTemplate({ name, description, structure: parsed }); else if (editing) await api.updateExternalFolderTemplate(editing.id, { name, description, structure: parsed }); await load(); setEditing(null); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not save template.', { variant: 'error' }); } finally { setBusy(false); } };
  const apply = async (template: Template) => { const destination = sources[0]?.provider_source_id; if (!destination) { toast.show('Connect a Google Drive folder to this project first.', { variant: 'error' }); return; } setBusy(true); try { const result = await api.createGoogleDriveProjectStructure(projectId, { template_id: template.id, destination_folder_id: destination, root_name: projectName, idempotency_key: `template:${projectId}:${template.id}:${Date.now()}` }) as { operation?: ExternalProviderOperation }; if (result.operation) setOperation(result.operation); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not apply folder template.', { variant: 'error' }); } finally { setBusy(false); } };
  const retry = async () => { if (!operation) return; setBusy(true); try { setOperation(await api.retryExternalProviderOperation(operation.id) as ExternalProviderOperation); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not retry failed folders.', { variant: 'error' }); } finally { setBusy(false); } };
  return <section className="mt-3 border-t border-[color:var(--ledger-border-subtle)] pt-3"><div className="flex items-center justify-between"><div><h3 className="text-xs font-semibold text-[var(--ledger-text-primary)]">Drive folder templates</h3><p className="mt-0.5 text-[11px] text-[var(--ledger-text-muted)]">Create a repeatable folder structure for this project.</p></div>{canEdit && <button type="button" onClick={() => openEditor('new')} className="inline-flex items-center gap-1 rounded-md border border-[color:var(--ledger-border-subtle)] px-2 py-1 text-[11px]"><Plus size={12} />New template</button>}</div>
    <div className="mt-2 space-y-1.5">{templates.map((template) => <div key={template.id} className="rounded-lg border border-[color:var(--ledger-border-subtle)] px-3 py-2"><div className="flex items-center gap-2"><span className="min-w-0 flex-1 truncate text-xs font-medium">{template.name}</span><span className="text-[11px] text-[var(--ledger-text-muted)]">{(template.structure?.folders || []).length} folders</span>{canEdit && <><button type="button" title="Preview" onClick={() => openEditor(template)} className="rounded p-1 hover:bg-[var(--ledger-surface-hover)]"><Pencil size={12} /></button><button type="button" title="Delete" onClick={() => { if (window.confirm(`Delete ${template.name}?`)) void api.deleteExternalFolderTemplate(template.id).then(load); }} className="rounded p-1 text-[var(--ledger-danger)] hover:bg-[var(--ledger-surface-hover)]"><Trash2 size={12} /></button><button type="button" disabled={busy} onClick={() => void apply(template)} className="rounded-md bg-[var(--ledger-accent)] px-2 py-1 text-[11px] text-white disabled:opacity-50">Apply</button></>}</div></div>)}</div>
    {operation && <div className="mt-3"><ExternalProviderOperationStatus operation={operation} onRetry={operation.status === 'failed' || operation.status === 'partially_completed' ? retry : undefined} /></div>}
    {editing && <ModalOverlay isOpen onClose={() => setEditing(null)} classNameContainer="w-full max-w-lg p-5"><h2 className="text-base font-semibold">{editing === 'new' ? 'Create folder template' : 'Edit folder template'}</h2><label className="mt-4 block text-xs font-medium">Name<input autoFocus value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-md border border-[color:var(--ledger-border-subtle)] bg-transparent px-2 py-2 text-sm" /></label><label className="mt-3 block text-xs font-medium">Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} className="mt-1 w-full rounded-md border border-[color:var(--ledger-border-subtle)] bg-transparent px-2 py-2 text-sm" rows={2} /></label><label className="mt-3 block text-xs font-medium">Folder structure JSON<textarea value={structure} onChange={(event) => setStructure(event.target.value)} className="mt-1 h-48 w-full rounded-md border border-[color:var(--ledger-border-subtle)] bg-transparent px-2 py-2 font-mono text-xs" /></label><div className="mt-2 text-[11px] text-[var(--ledger-text-muted)]">Preview: {folders.map((folder) => folder.name).join(' · ') || 'No folders'}</div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setEditing(null)} className="rounded-md px-3 py-2 text-xs">Cancel</button><button type="button" disabled={busy || !name.trim()} onClick={() => void save()} className="rounded-md bg-[var(--ledger-accent)] px-3 py-2 text-xs text-white disabled:opacity-50">Save template</button></div></ModalOverlay>}
  </section>;
}
