-- Polish the built-in Ledger templates without touching user-created templates
-- or notes that were already created from them.
--
-- The library is workspace-scoped and is provisioned by the function introduced
-- in 081. Keep the content cleanup in one function so existing workspaces and
-- future workspaces receive the same templates.

CREATE OR REPLACE FUNCTION public.polish_ledger_template_content(
  template_name TEXT,
  source_html TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  CASE template_name
    WHEN 'Meeting Notes' THEN
      RETURN '<h1>Meeting Notes</h1><p><strong>Date and time:</strong><br><strong>Meeting lead:</strong><br><strong>Attendees:</strong><br><strong>Location or call:</strong></p><h2>Purpose</h2><p><em>What should this meeting accomplish?</em></p><h2>Agenda</h2><ol><li>Topic and desired outcome</li><li>Topic and desired outcome</li></ol><h2>Discussion</h2><h3>Topic 1</h3><p><em>Capture the useful context, questions, and alternatives.</em></p><h3>Topic 2</h3><p><em>Capture the useful context, questions, and alternatives.</em></p><h2>Decisions</h2><ul><li><strong>Decision:</strong> What was decided and why?</li></ul><h2>Action items</h2><ul><li>[ ] Action<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Questions and blockers</h2><ul><li>Question, blocker, or dependency:</li></ul><h2>Follow-ups</h2><ul><li>[ ] Message, resource, or check-in<br><strong>Owner:</strong></li></ul><h2>Next meeting</h2><p><strong>Date:</strong><br><strong>Preparation:</strong><br><strong>Topics to revisit:</strong></p><h2>Summary to share</h2><p><em>Write the concise update the team should receive.</em></p>';
    WHEN 'Project Brief' THEN
      RETURN '<h1>Project Brief</h1><p><strong>Project name:</strong><br><strong>Owner:</strong><br><strong>Team:</strong><br><strong>Target date:</strong></p><h2>Background</h2><p><em>What prompted this project?</em></p><h2>Objective</h2><p><em>What outcome are we trying to create?</em></p><h2>Success criteria</h2><ul><li>How will we know this worked?</li><li>What should be true when it is complete?</li></ul><h2>Scope</h2><ul><li>Included:</li></ul><h2>Out of scope</h2><ul><li>Explicitly not included:</li></ul><h2>Deliverables</h2><ol><li>Deliverable and acceptance signal</li><li>Deliverable and acceptance signal</li></ol><h2>Timeline and milestones</h2><ul><li><strong>Milestone:</strong> Target date</li></ul><h2>Short-term next actions</h2><ul><li>[ ] Action<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Long-term work</h2><ul><li>Workstream and next milestone:</li></ul><h2>Stakeholders and dependencies</h2><ul><li>Person, team, or dependency:</li></ul><h2>Risks and blockers</h2><ul><li>Risk or blocker, impact, and response:</li></ul><h2>Open questions</h2><ul><li>Question:</li></ul><h2>Linked resources</h2><ul><li>Resource and why it matters:</li></ul>';
    WHEN 'Daily Reflection' THEN
      RETURN '<h1>Daily Reflection</h1><p><strong>Date:</strong><br><strong>Energy:</strong> Energized / steady / drained</p><h2>Finished</h2><ul><li>What did I complete?</li></ul><h2>What moved forward</h2><p><em>Capture progress that matters, even if it is not finished.</em></p><h2>What was blocked</h2><ul><li>What is stuck, and what would unblock it?</li></ul><h2>Short-term follow-ups</h2><ul><li>[ ] Follow-up<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Long-term progress</h2><p><em>What did I advance for a project or future deadline?</em></p><h2>What I learned</h2><ul><li>Lesson, insight, or pattern:</li></ul><h2>What needs attention</h2><ul><li>Important item to carry forward:</li></ul><h2>First task tomorrow</h2><p><strong>Start with:</strong></p><h2>Notes</h2><p><em>Anything else worth remembering?</em></p>';
    WHEN 'Book Notes' THEN
      RETURN '<h1>Book Notes</h1><p><strong>Title:</strong><br><strong>Author:</strong><br><strong>Started:</strong><br><strong>Finished:</strong></p><h2>Why I chose this book</h2><p><em>What question, need, or curiosity brought me here?</em></p><h2>Main argument</h2><p><em>Summarize the author''s central idea in your own words.</em></p><h2>Chapter notes</h2><ol><li>Chapter or section — key idea</li><li>Chapter or section — key idea</li></ol><h2>Key takeaways</h2><ul><li>Important concept or lesson:</li><li>Important concept or lesson:</li></ul><h2>Quotes</h2><blockquote><p>“Quote” — page</p></blockquote><h2>Questions</h2><ul><li>Question or unresolved tension:</li></ul><h2>Connections</h2><p><em>What does this connect to in your work, life, or other ideas?</em></p><h2>How I will apply this</h2><ol><li>Action or experiment</li><li>Conversation or project to inform</li></ol><h2>Follow-up reading</h2><ul><li>Book, article, or person to explore:</li></ul><h2>Rating</h2><p>★★★★☆</p>';
    WHEN 'Weekly Internship Workspace' THEN
      RETURN '<h1>Week of</h1><p><strong>Role or team:</strong><br><strong>Supervisor:</strong><br><strong>Week starting:</strong></p><h2>Main goals</h2><ol><li>Goal and why it matters</li><li>Goal and why it matters</li></ol><h2>Daily overview</h2><h3>Monday</h3><p><em>Plan, progress, and questions:</em></p><h3>Tuesday</h3><p><em>Plan, progress, and questions:</em></p><h3>Wednesday</h3><p><em>Plan, progress, and questions:</em></p><h3>Thursday</h3><p><em>Plan, progress, and questions:</em></p><h3>Friday</h3><p><em>Plan, progress, and questions:</em></p><h2>Short-term tasks</h2><ul><li>[ ] Task<br><strong>Due:</strong></li></ul><h2>Long-term work</h2><ul><li>Workstream, milestone, and next step:</li></ul><h2>Meetings and communication</h2><ul><li>[ ] Person or channel, message, and follow-up:</li></ul><h2>Work completed</h2><ul><li>Outcome or artifact:</li></ul><h2>Feedback and skills</h2><ul><li>Feedback received:</li><li>Skill practiced:</li></ul><h2>Questions and blockers</h2><ul><li>Question, blocker, or support needed:</li></ul><h2>Next week</h2><ol><li>Priority to carry forward</li><li>First task</li></ol>';
    WHEN 'Team Meeting Notes' THEN
      RETURN '<h1>Team Meeting</h1><p><strong>Date and time:</strong><br><strong>Meeting lead:</strong><br><strong>Attendees:</strong><br><strong>Location or call:</strong></p><h2>Desired outcome</h2><p><em>What should be clear or decided by the end?</em></p><h2>Agenda</h2><ol><li>Topic and owner</li><li>Topic and owner</li></ol><h2>Updates</h2><ul><li>Team or project update:</li></ul><h2>Discussion</h2><h3>Main room notes</h3><p><em>Capture the important context and open questions.</em></p><h3>Breakout room notes</h3><p><em>Capture the useful report-back.</em></p><h2>Decisions</h2><ul><li><strong>Decision:</strong> Outcome and rationale</li></ul><h2>Short-term tasks</h2><ul><li>[ ] Task<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Long-term work</h2><ul><li>Workstream<br><strong>Owner:</strong><br><strong>Target:</strong></li></ul><h2>Questions and blockers</h2><ul><li>Question, blocker, or dependency:</li></ul><h2>Follow-ups</h2><ul><li>[ ] Message, resource, or check-in:</li></ul><h2>Next meeting</h2><p><strong>Date:</strong><br><strong>Topics to revisit:</strong><br><strong>Preparation:</strong></p>';
    WHEN 'Breakout Room Notes' THEN
      RETURN '<h1>Breakout Room Notes</h1><p><strong>Topic:</strong><br><strong>People present:</strong><br><strong>Facilitator:</strong></p><h2>Goal</h2><p><em>What should this group resolve or produce?</em></p><h2>Discussion</h2><p><em>Capture the useful reasoning, examples, and open questions.</em></p><h2>Ideas considered</h2><ul><li>Idea and implication:</li></ul><h2>Decisions</h2><ul><li>Decision and rationale:</li></ul><h2>Assigned tasks</h2><ul><li>[ ] Task<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Questions to bring back</h2><ol><li>Question for the main room</li><li>Question for the main room</li></ol><h2>Main-room update</h2><p><em>Write the concise summary to report back.</em></p><h2>Follow-ups</h2><ul><li>[ ] Follow-up:</li></ul>';
    WHEN 'Formal Meeting Minutes' THEN
      RETURN '<h1>Meeting Minutes</h1><p><strong>Meeting:</strong><br><strong>Date and time:</strong><br><strong>Location or call:</strong><br><strong>Facilitator:</strong><br><strong>Minutes prepared by:</strong></p><h2>Attendees</h2><ul><li>Name and role</li></ul><h2>Absent</h2><ul><li>Name and role</li></ul><h2>Agenda</h2><ol><li>Agenda item</li><li>Agenda item</li></ol><h2>Discussion by topic</h2><h3>Topic 1</h3><p><strong>Summary:</strong> Relevant discussion and context.<br><strong>Decision:</strong> Outcome or “no decision.”</p><h2>Decisions</h2><ul><li>Decision, reasoning, and people involved:</li></ul><h2>Action items</h2><ul><li>[ ] Action<br><strong>Owner:</strong><br><strong>Deadline:</strong></li></ul><h2>Items carried forward</h2><ul><li>Open item and why it remains open:</li></ul><h2>Next meeting</h2><p><strong>Date:</strong><br><strong>Time:</strong><br><strong>Location:</strong></p><h2>Distribution</h2><p><em>Who should receive these minutes?</em></p><h2>Final summary</h2><p><em>Summarize the outcome in two or three sentences.</em></p>';
    WHEN 'Team Lead Weekly Overview' THEN
      RETURN '<h1>Team Lead Weekly Overview</h1><p><strong>Week of:</strong><br><strong>Team:</strong><br><strong>Prepared by:</strong></p><h2>Team priorities</h2><ol><li>Priority and desired outcome</li><li>Priority and desired outcome</li><li>Priority and desired outcome</li></ol><h2>Main outcome for the week</h2><p><em>What should be meaningfully different by the end of the week?</em></p><h2>Short-term work</h2><p>Work expected this week.</p><ul><li>[ ] Task<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Long-term work</h2><p>Ongoing work connected to projects or future deadlines.</p><ul><li>Workstream<br><strong>Owner:</strong><br><strong>Target:</strong></li></ul><h2>Assignments by person</h2><h3>Team member</h3><p><strong>Current work:</strong><br><strong>Support needed:</strong><br><strong>Next step:</strong></p><h2>Work completed</h2><ul><li>Outcome or milestone:</li></ul><h2>Work in progress</h2><ul><li>Workstream, status, and next step:</li></ul><h2>Blockers and dependencies</h2><ul><li>Blocker, owner, and response:</li></ul><h2>People needing support</h2><ul><li>Person, context, and support:</li></ul><h2>Follow-ups</h2><ul><li>[ ] Follow-up<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Upcoming deadlines</h2><ol><li>Deadline and owner</li></ol><h2>Meetings</h2><ul><li>Meeting, purpose, and preparation:</li></ul><h2>Communication to send</h2><ul><li>[ ] Audience, message, and channel:</li></ul><h2>Decisions needed</h2><ul><li>Decision and required-by date:</li></ul><h2>Risks</h2><ul><li>Risk, impact, and mitigation:</li></ul><h2>Wins</h2><ul><li>Progress worth recognizing:</li></ul><h2>Next week preparation</h2><ol><li>Priority to carry forward</li><li>First action</li></ol>';
    WHEN 'One-on-One Notes' THEN
      RETURN '<h1>One-on-One Notes</h1><p><strong>Person:</strong><br><strong>Date:</strong><br><strong>Meeting lead:</strong></p><h2>Check-in</h2><p><em>How are things going, and what context should shape this conversation?</em></p><h2>Current priorities</h2><ul><li>Priority, status, and next step:</li></ul><h2>Wins</h2><ul><li>Progress worth recognizing:</li></ul><h2>Challenges and workload</h2><p><em>What feels difficult, unclear, or competing for attention?</em></p><h2>Feedback</h2><ul><li><strong>Given:</strong></li><li><strong>Received:</strong></li></ul><h2>Support needed</h2><ul><li>Support, decision, or resource:</li></ul><h2>Short-term tasks</h2><ul><li>[ ] Task<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Development</h2><p><em>Skills, responsibilities, or opportunities to build over time.</em></p><h2>Decisions and follow-ups</h2><ul><li>[ ] Follow-up<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Topics for next time</h2><ol><li>Topic:</li></ol>';
    WHEN 'Project Kickoff Meeting' THEN
      RETURN '<h1>Project Kickoff</h1><p><strong>Project:</strong><br><strong>Date:</strong><br><strong>Facilitator:</strong><br><strong>Participants:</strong></p><h2>Purpose</h2><p><em>Why are we doing this work now?</em></p><h2>Desired outcome</h2><p><em>What will be true when this project succeeds?</em></p><h2>Scope</h2><ul><li>Included:</li><li>Out of scope:</li></ul><h2>Roles</h2><ul><li><strong>Area:</strong> Owner and responsibility</li></ul><h2>Deliverables</h2><ol><li>Deliverable and acceptance signal</li></ol><h2>Timeline</h2><ul><li><strong>Milestone:</strong> Target date</li></ul><h2>Risks and dependencies</h2><ul><li>Risk or dependency, owner, and response:</li></ul><h2>Communication plan</h2><p><em>Where will updates live, who needs them, and how often?</em></p><h2>Next actions</h2><ul><li>[ ] Action<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Decisions and open questions</h2><ul><li>Decision or question:</li></ul><h2>Next checkpoint</h2><p><strong>Date:</strong><br><strong>Preparation:</strong></p>';
    WHEN 'Retrospective' THEN
      RETURN '<h1>Retrospective</h1><p><strong>Period or project:</strong><br><strong>Date:</strong><br><strong>Participants:</strong></p><h2>What went well</h2><ul><li>Practice or outcome to preserve:</li></ul><h2>What did not go well</h2><ul><li>Friction or outcome to understand:</li></ul><h2>What surprised us</h2><p><em>Capture something unexpected and what it changed.</em></p><h2>Patterns</h2><ul><li><strong>Communication:</strong></li><li><strong>Process:</strong></li><li><strong>Dependencies:</strong></li></ul><h2>Decisions</h2><ul><li>Decision and rationale:</li></ul><h2>Stop, start, continue</h2><ol><li><strong>Stop:</strong> Practice to remove</li><li><strong>Start:</strong> Practice to introduce</li><li><strong>Continue:</strong> Practice to preserve</li></ol><h2>Improvements</h2><ul><li>[ ] Improvement<br><strong>Owner:</strong><br><strong>Review date:</strong></li></ul>';
    WHEN 'Daily Internship Log' THEN
      RETURN '<h1>Internship Log</h1><p><strong>Date:</strong><br><strong>Hours worked:</strong><br><strong>Supervisor or team:</strong></p><h2>Today''s priorities</h2><ol><li>Priority</li><li>Priority</li></ol><h2>Completed</h2><ul><li>Task and outcome:</li></ul><h2>In progress</h2><ul><li>Workstream and current status:</li></ul><h2>Next steps</h2><ul><li>[ ] Task and due date:</li></ul><h2>Meetings and communication</h2><ul><li>Conversation, update, or follow-up:</li></ul><h2>Feedback and learning</h2><ul><li>Feedback received:</li><li>Skill or process practiced:</li></ul><h2>Questions and blockers</h2><ul><li>Question or blocker:</li></ul><h2>Tomorrow''s first task</h2><p><strong>Start with:</strong></p>';
    WHEN 'Supervisor Meeting Notes' THEN
      RETURN '<h1>Supervisor Meeting</h1><p><strong>Supervisor:</strong><br><strong>Date:</strong><br><strong>Purpose:</strong></p><h2>Updates since last meeting</h2><ul><li>Progress, outcome, or change:</li></ul><h2>Work completed</h2><ul><li>Completed task and evidence:</li></ul><h2>Current priorities</h2><ol><li>Priority and next step</li></ol><h2>Assignments</h2><ul><li>[ ] Assignment<br><strong>Due:</strong></li></ul><h2>Feedback</h2><p><em>What feedback should I ask for or record?</em></p><h2>Clarifications and questions</h2><ol><li>Question:</li></ol><h2>Decisions and deadlines</h2><ul><li>Decision or deadline:</li></ul><h2>Follow-ups</h2><ul><li>[ ] Follow-up<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Prepare for next meeting</h2><ul><li>Item to bring:</li></ul>';
    WHEN 'Internship Evaluation Prep' THEN
      RETURN '<h1>Internship Evaluation Prep</h1><p><strong>Placement:</strong><br><strong>Organization:</strong><br><strong>Evaluation date:</strong></p><h2>Original goals</h2><ol><li>Goal and expected outcome</li></ol><h2>Responsibilities</h2><ul><li>Responsibility and result:</li></ul><h2>Accomplishments</h2><ul><li>Outcome, evidence, or artifact:</li></ul><h2>Skills developed</h2><ul><li><strong>Technical:</strong></li><li><strong>Communication:</strong></li><li><strong>Time management:</strong></li></ul><h2>Feedback received</h2><blockquote><p>Useful feedback to remember:</p></blockquote><h2>Challenges and lessons</h2><ul><li>Challenge and what I learned:</li></ul><h2>Portfolio work</h2><ul><li>Project or artifact to document:</li></ul><h2>Questions for the evaluation</h2><ol><li>Question:</li></ol><h2>Next steps</h2><ul><li>[ ] Action<br><strong>Due:</strong></li></ul>';
    WHEN 'Internship Portfolio Case Study' THEN
      RETURN '<h1>Internship Portfolio Case Study</h1><p><strong>Project:</strong><br><strong>Organization:</strong><br><strong>Role:</strong><br><strong>Timeline:</strong></p><h2>Background</h2><p><em>What situation or opportunity led to this work?</em></p><h2>Problem and objective</h2><ul><li><strong>Problem:</strong></li><li><strong>Objective:</strong></li></ul><h2>Audience and constraints</h2><ul><li><strong>Audience:</strong></li><li><strong>Constraints:</strong></li></ul><h2>My responsibilities</h2><ul><li>Responsibility and contribution:</li></ul><h2>Process</h2><ol><li>Research or discovery</li><li>Approach and decisions</li><li>Feedback and revisions</li></ol><h2>Final outcome</h2><p><em>What shipped, changed, or was learned?</em></p><h2>Results</h2><ul><li>Evidence or impact:</li></ul><h2>Skills demonstrated</h2><ul><li>Skill and example:</li></ul><h2>What I learned</h2><h2>What I would improve</h2><h2>Portfolio assets</h2><ul><li>[ ] Asset to collect or prepare:</li></ul>';
    WHEN 'Team Meeting Agenda' THEN
      RETURN '<h1>Team Meeting Agenda</h1><p><strong>Date and time:</strong><br><strong>Facilitator:</strong><br><strong>Attendees:</strong><br><strong>Note taker:</strong></p><h2>Purpose</h2><p><em>What should be clear or decided by the end?</em></p><h2>Updates</h2><ul><li>Update and owner:</li></ul><h2>Priority topics</h2><ol><li><strong>Topic:</strong> Owner and desired decision</li><li><strong>Topic:</strong> Owner and desired decision</li></ol><h2>Decisions needed</h2><ul><li>Decision and required-by date:</li></ul><h2>Short-term work review</h2><ul><li>Task, owner, and status:</li></ul><h2>Long-term project review</h2><ul><li>Project, milestone, and risk:</li></ul><h2>Blockers and support</h2><ul><li>Blocker or request:</li></ul><h2>Announcements</h2><h2>Breakout topics</h2><ul><li>Topic and desired report-back:</li></ul><h2>Time allocation</h2><ol><li>Topic — minutes</li></ol>';
    WHEN 'Team Weekly Update' THEN
      RETURN '<h1>Team Weekly Update</h1><p><strong>Week of:</strong><br><strong>Prepared by:</strong><br><strong>Audience:</strong></p><h2>Summary</h2><p><em>What is the most important thing to know this week?</em></p><h2>Wins</h2><ul><li>Progress worth recognizing:</li></ul><h2>Completed</h2><ul><li>Outcome or milestone:</li></ul><h2>In progress</h2><ul><li>Workstream, status, and next step:</li></ul><h2>Priorities</h2><ol><li>Short-term priority</li><li>Long-term priority</li></ol><h2>Blockers and decisions</h2><ul><li>Blocker or decision needed:</li></ul><h2>Upcoming deadlines</h2><ul><li>Deadline, owner, and context:</li></ul><h2>Support needed</h2><ul><li>Person, request, and by when:</li></ul><h2>Communication</h2><ul><li>Message or audience:</li></ul><h2>Next week</h2><p><strong>First priority:</strong></p>';
    WHEN 'Delegation Brief' THEN
      RETURN '<h1>Delegation Brief</h1><p><strong>Assignment:</strong><br><strong>Assigned to:</strong><br><strong>Owner:</strong><br><strong>Deadline:</strong></p><h2>Why this matters</h2><p><em>What outcome does this support?</em></p><h2>Desired outcome</h2><p><em>What should be true when the work is complete?</em></p><h2>Scope</h2><ul><li>Included:</li><li>Out of scope:</li></ul><h2>Resources and context</h2><ul><li>Document, person, or reference:</li></ul><h2>Dependencies and risks</h2><ul><li>Dependency, risk, or constraint:</li></ul><h2>Definition of done</h2><ol><li>Acceptance criterion</li><li>Acceptance criterion</li></ol><h2>Check-in</h2><p><strong>Date:</strong><br><strong>Format:</strong></p><h2>Questions</h2><ul><li>Question or clarification:</li></ul><h2>Follow-up plan</h2><ul><li>[ ] Follow-up<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul>';
    WHEN 'Team Onboarding Notes' THEN
      RETURN '<h1>Team Onboarding Notes</h1><p><strong>Person:</strong><br><strong>Role:</strong><br><strong>Start date:</strong><br><strong>Manager:</strong></p><h2>Team overview</h2><p><em>What should this person understand about how the team works?</em></p><h2>Key people</h2><ul><li>Name, role, and when to involve them:</li></ul><h2>Current projects</h2><ul><li>Project, context, and first contribution:</li></ul><h2>Tools and access</h2><ul><li>[ ] Tool or access request:</li></ul><h2>Important documents</h2><ul><li>Document and why it matters:</li></ul><h2>Communication norms</h2><ul><li>Norm, channel, or cadence:</li></ul><h2>Recurring meetings</h2><ul><li>Meeting, purpose, and preparation:</li></ul><h2>First week</h2><ol><li>Milestone or task</li><li>Milestone or task</li></ol><h2>First month</h2><ol><li>Goal and evidence</li></ol><h2>Questions and follow-ups</h2><ul><li>[ ] Follow-up<br><strong>Owner:</strong></li></ul>';
    WHEN 'Decision Log' THEN
      RETURN '<h1>Decision Log</h1><p><strong>Date:</strong><br><strong>Decision:</strong><br><strong>Related project:</strong><br><strong>Owner:</strong></p><h2>Context</h2><p><em>What situation required a decision?</em></p><h2>Options considered</h2><ol><li>Option and tradeoff</li><li>Option and tradeoff</li></ol><h2>Final choice</h2><p><em>State the decision clearly.</em></p><h2>Reasoning</h2><ul><li>Evidence or principle behind the choice:</li></ul><h2>People involved</h2><ul><li>Name and role:</li></ul><h2>Impact and risks</h2><ul><li>Expected impact:</li><li>Risk to monitor:</li></ul><h2>Follow-up actions</h2><ul><li>[ ] Action<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Review date</h2><p><strong>Revisit on:</strong></p>';
    WHEN 'Creative Brief' THEN
      RETURN '<h1>Creative Brief</h1><p><strong>Project:</strong><br><strong>Client or stakeholder:</strong><br><strong>Owner:</strong><br><strong>Due date:</strong></p><h2>Background</h2><p><em>What is happening and why does this work matter?</em></p><h2>Objective</h2><h2>Audience</h2><p><strong>Who:</strong><br><strong>Need or tension:</strong></p><h2>Key message</h2><blockquote><p>If the audience remembers one thing, it is:</p></blockquote><h2>Deliverables</h2><ul><li>Deliverable and format:</li></ul><h2>Requirements and constraints</h2><ul><li>Requirement:</li><li>Constraint:</li></ul><h2>Tone and direction</h2><ul><li>Should feel:</li><li>Should avoid:</li></ul><h2>References</h2><ul><li>Reference and what to borrow:</li></ul><h2>Timeline and approval</h2><ol><li>Milestone and date</li></ol><h2>Next actions</h2><ul><li>[ ] Action<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Open questions</h2><ul><li>Question:</li></ul>';
    WHEN 'Project Status Update' THEN
      RETURN '<h1>Project Status Update</h1><p><strong>Project:</strong><br><strong>Date:</strong><br><strong>Owner:</strong><br><strong>Overall status:</strong></p><h2>Summary</h2><p><em>What is the clearest one-paragraph update?</em></p><h2>Completed</h2><ul><li>Outcome or milestone:</li></ul><h2>In progress</h2><ul><li>Workstream, status, and next step:</li></ul><h2>Next actions</h2><ul><li>[ ] Action<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Milestones</h2><ol><li>Milestone — date — status</li></ol><h2>Risks and blockers</h2><ul><li>Risk, impact, and response:</li></ul><h2>Dependencies</h2><ul><li>Dependency and owner:</li></ul><h2>Decisions needed</h2><ul><li>Decision and required-by date:</li></ul><h2>Timeline changes</h2><p><em>What changed, and why?</em></p><h2>Next update</h2><p><strong>Date:</strong><br><strong>Focus:</strong></p>';
    WHEN 'Project Handoff' THEN
      RETURN '<h1>Project Handoff</h1><p><strong>Project:</strong><br><strong>Handoff from:</strong><br><strong>Handoff to:</strong><br><strong>Date:</strong></p><h2>Current status</h2><p><em>Where does the project stand right now?</em></p><h2>Objective and success criteria</h2><ul><li>Objective:</li><li>Success signal:</li></ul><h2>Completed work</h2><ul><li>Outcome, artifact, or decision:</li></ul><h2>Open work</h2><ul><li>Workstream and next action:</li></ul><h2>Priorities</h2><ol><li>Immediate priority</li><li>Longer-term priority</li></ol><h2>Resources and access</h2><ul><li>File, system, or person:</li></ul><h2>Decisions and known issues</h2><ul><li>Decision or issue and context:</li></ul><h2>Stakeholders and dependencies</h2><ul><li>Person, team, or dependency:</li></ul><h2>Upcoming deadlines</h2><ul><li>Deadline and owner:</li></ul><h2>Successful handoff</h2><p><em>What should the receiving owner be able to do next?</em></p><h2>Questions</h2><ul><li>Question to resolve:</li></ul>';
    WHEN 'Project Postmortem' THEN
      RETURN '<h1>Project Postmortem</h1><p><strong>Project:</strong><br><strong>Outcome:</strong><br><strong>Date:</strong><br><strong>Participants:</strong></p><h2>Original objective</h2><p><em>What were we trying to accomplish?</em></p><h2>Final result</h2><p><em>What actually happened?</em></p><h2>What went well</h2><ul><li>Practice or outcome to preserve:</li></ul><h2>What went poorly</h2><ul><li>Friction or outcome to understand:</li></ul><h2>Timeline and scope</h2><ul><li>Change, cause, and impact:</li></ul><h2>Communication and decisions</h2><ul><li>Lesson or decision:</li></ul><h2>Risks encountered</h2><ul><li>Risk, signal, and response:</li></ul><h2>Lessons learned</h2><ol><li>Lesson and how to apply it</li></ol><h2>Short-term fixes</h2><ul><li>[ ] Fix<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Long-term improvements</h2><ul><li>Improvement and expected impact:</li></ul><h2>Review date</h2><p><strong>Revisit on:</strong></p>';
    WHEN 'Research Notes' THEN
      RETURN '<h1>Research Notes</h1><p><strong>Research question:</strong><br><strong>Project:</strong><br><strong>Date:</strong><br><strong>Owner:</strong></p><h2>Context and goal</h2><p><em>What do we need to understand, and why?</em></p><h2>Sources</h2><ul><li>Source, date, and relevance:</li></ul><h2>Key findings</h2><ol><li>Finding and supporting evidence</li><li>Finding and supporting evidence</li></ol><h2>Evidence</h2><blockquote><p>Useful quote, data point, or observation:</p></blockquote><h2>Contradictions and questions</h2><ul><li>Question or disagreement:</li></ul><h2>Implications</h2><p><em>What might this change about the work?</em></p><h2>Decisions influenced</h2><ul><li>Decision and connection to research:</li></ul><h2>Follow-up research</h2><ul><li>[ ] Question or source to explore:</li></ul><h2>Next actions</h2><ul><li>[ ] Action<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul>';
    WHEN 'Weekly Review' THEN
      RETURN '<h1>Weekly Review</h1><p><strong>Week of:</strong><br><strong>Reviewed on:</strong></p><h2>Wins</h2><ul><li>Progress worth recognizing:</li></ul><h2>Work completed</h2><ul><li>Outcome or milestone:</li></ul><h2>What carried over</h2><ul><li>Task, reason, and next step:</li></ul><h2>What was blocked</h2><ul><li>Blocker and what would unblock it:</li></ul><h2>Follow-ups</h2><ul><li>[ ] Person, message, or commitment<br><strong>Due:</strong></li></ul><h2>Projects needing attention</h2><ul><li>Project and next action:</li></ul><h2>Lessons</h2><ol><li>Lesson or pattern:</li></ol><h2>Stop and continue</h2><ul><li><strong>Stop:</strong></li><li><strong>Continue:</strong></li></ul><h2>Priorities for next week</h2><ol><li>Priority and desired outcome</li><li>Priority and desired outcome</li></ol><h2>First task Monday</h2><p><strong>Start with:</strong></p>';
    WHEN 'Monthly Reset' THEN
      RETURN '<h1>Monthly Reset</h1><p><strong>Month reviewed:</strong><br><strong>Reset date:</strong></p><h2>Highlights</h2><ul><li>Moment, outcome, or memory worth keeping:</li></ul><h2>Completed goals</h2><ul><li>Goal and result:</li></ul><h2>Incomplete goals</h2><ul><li>Goal, reason, and decision:</li></ul><h2>Areas of life</h2><ul><li><strong>Work:</strong></li><li><strong>Relationships:</strong></li><li><strong>Learning:</strong></li><li><strong>Health or energy:</strong></li><li><strong>Administration:</strong></li></ul><h2>What worked</h2><p><em>Which systems, habits, or choices helped?</em></p><h2>What felt heavy</h2><p><em>What should be simplified, stopped, or addressed?</em></p><h2>Important dates</h2><ul><li>Date and context:</li></ul><h2>Next month focus</h2><ol><li>Priority and why it matters</li><li>Priority and why it matters</li></ol><h2>First actions</h2><ul><li>[ ] Action<br><strong>Due:</strong></li></ul>';
    WHEN 'Decision Journal' THEN
      RETURN '<h1>Decision Journal</h1><p><strong>Decision:</strong><br><strong>Date:</strong><br><strong>Review date:</strong></p><h2>Context</h2><p><em>What situation requires a choice?</em></p><h2>Why this matters</h2><h2>Options</h2><ol><li>Option and tradeoff</li><li>Option and tradeoff</li></ol><h2>Assumptions</h2><ul><li>Assumption to test:</li></ul><h2>Risks</h2><ul><li>Risk and mitigation:</li></ul><h2>What I know and do not know</h2><ul><li><strong>Know:</strong></li><li><strong>Need to learn:</strong></li></ul><h2>Final decision</h2><p><em>State the choice clearly.</em></p><h2>Reasoning</h2><p><em>Why this option now?</em></p><h2>Follow-up actions</h2><ul><li>[ ] Action<br><strong>Owner:</strong><br><strong>Due:</strong></li></ul><h2>Outcome review</h2><p><em>Complete this after the review date.</em></p>';
    WHEN 'Brain Dump to Action Plan' THEN
      RETURN '<h1>Brain Dump to Action Plan</h1><h2>Everything on my mind</h2><p><em>Write freely first. Sort it after.</em></p><h2>Sort the list</h2><ul><li><strong>Urgent:</strong></li><li><strong>Important:</strong></li><li><strong>Can wait:</strong></li><li><strong>Delegate:</strong></li></ul><h2>Short-term tasks</h2><ul><li>[ ] Task and smallest next action:</li></ul><h2>Long-term work</h2><ul><li>Workstream and next milestone:</li></ul><h2>Projects</h2><ul><li>Project and why it matters:</li></ul><h2>Follow-ups</h2><ul><li>[ ] Person, message, or commitment:</li></ul><h2>Events and deadlines</h2><ul><li>Date, event, or deadline:</li></ul><h2>Questions</h2><ul><li>Question to resolve:</li></ul><h2>First three actions</h2><ol><li>[ ] First action</li><li>[ ] Second action</li><li>[ ] Third action</li></ol>';
    WHEN 'Learning Log' THEN
      RETURN '<h1>Learning Log</h1><p><strong>Topic:</strong><br><strong>Date:</strong><br><strong>Why I am learning this:</strong></p><h2>Key concepts</h2><ul><li>Concept and definition:</li></ul><h2>Notes and examples</h2><p><em>Explain the idea in your own words.</em></p><h2>Questions</h2><ol><li>Question:</li></ol><h2>What confused me</h2><h2>What clicked</h2><h2>Practical application</h2><ul><li>Where could I use this?</li></ul><h2>Practice task</h2><ul><li>[ ] Practice or experiment:</li></ul><h2>Resources</h2><ul><li>Resource and why it helps:</li></ul><h2>Next learning step</h2><p><strong>Continue with:</strong></p>';
    WHEN 'Article Notes' THEN
      RETURN '<h1>Article Notes</h1><p><strong>Title:</strong><br><strong>Author:</strong><br><strong>Source:</strong><br><strong>Date:</strong><br><strong>Link:</strong></p><h2>Why I saved this</h2><p><em>What question or problem does this help with?</em></p><h2>Summary</h2><p><em>Capture the argument in two or three sentences.</em></p><h2>Main argument</h2><h2>Evidence</h2><ul><li>Evidence, example, or data point:</li></ul><h2>Key takeaways</h2><ol><li>Takeaway:</li><li>Takeaway:</li></ol><h2>Useful quotes</h2><blockquote><p>“Quote” — source</p></blockquote><h2>Questions and challenges</h2><ul><li>Question, disagreement, or tension:</li></ul><h2>Application</h2><ul><li>How this could affect my work or decisions:</li></ul><h2>Related projects</h2><ul><li>Project or note:</li></ul><h2>Follow-up</h2><ul><li>[ ] Action or resource to explore:</li></ul>';
    WHEN 'Course or Lecture Notes' THEN
      RETURN '<h1>Course or Lecture Notes</h1><p><strong>Course:</strong><br><strong>Session:</strong><br><strong>Date:</strong><br><strong>Instructor:</strong><br><strong>Topic:</strong></p><h2>Learning objectives</h2><ol><li>By the end, I should understand:</li></ol><h2>Main concepts</h2><ul><li>Concept and explanation:</li></ul><h2>Definitions</h2><ul><li><strong>Term:</strong> Definition</li></ul><h2>Examples</h2><ul><li>Example and why it matters:</li></ul><h2>Questions</h2><ul><li>Question to revisit:</li></ul><h2>Assignments</h2><ul><li>[ ] Assignment and due date:</li></ul><h2>Study plan</h2><ol><li>[ ] Short-term study task</li><li>[ ] Longer-term review task</li></ol><h2>Resources</h2><ul><li>Resource:</li></ul><h2>Summary</h2><p><em>Explain the session in your own words.</em></p><h2>Next review</h2><p><strong>Date:</strong></p>';
    WHEN 'Podcast Notes' THEN
      RETURN '<h1>Podcast Notes</h1><p><strong>Podcast:</strong><br><strong>Episode:</strong><br><strong>Guest:</strong><br><strong>Date:</strong><br><strong>Link:</strong></p><h2>Why I listened</h2><p><em>What was I hoping to learn?</em></p><h2>Main topics</h2><ol><li>Topic:</li><li>Topic:</li></ol><h2>Key ideas</h2><ul><li>Idea and why it matters:</li></ul><h2>Useful quotes</h2><blockquote><p>“Quote” — timestamp</p></blockquote><h2>People and resources mentioned</h2><ul><li>Person, book, tool, or link:</li></ul><h2>Questions</h2><ul><li>Question to explore:</li></ul><h2>Actionable takeaways</h2><ol><li>[ ] Action or experiment</li><li>[ ] Conversation or follow-up</li></ol><h2>Rating and follow-up</h2><p><strong>Rating:</strong> ★★★★☆<br><strong>Next:</strong></p>';
    ELSE
      -- Many of the expanded presets are intentionally lightweight. Add a
      -- quiet writing prompt after heading-only sections so they read as
      -- usable scaffolds instead of a wall of labels.
      RETURN regexp_replace(
        regexp_replace(
          COALESCE(source_html, ''),
          '(<h[2-3][^>]*>[^<]+</h[2-3]>)(<h[2-3])',
          '\1<p><em>Capture the key context, decision, or next step here.</em></p>\2',
          'g'
        ),
        '(<h[2-3][^>]*>[^<]+</h[2-3]>)$',
        '\1<p><em>Capture the key context, decision, or next step here.</em></p>'
      );
  END CASE;
END;
$$;

-- Update only Ledger-owned system rows. User-created templates and notes made
-- from older versions remain untouched.
UPDATE public.note_templates
SET content_html = public.polish_ledger_template_content(name, content_html),
    updated_at = NOW()
WHERE is_system = true;

-- Ensure future workspace provisioning uses the polished content too.
CREATE OR REPLACE FUNCTION public.provision_ledger_note_templates(target_workspace_id UUID)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE preset RECORD;
BEGIN
  FOR preset IN SELECT * FROM public.ledger_template_presets() LOOP
    INSERT INTO public.note_templates (
      workspace_id, system_key, name, category, description, title_pattern,
      content_html, is_default, is_system, visibility, created_by, usage_count
    ) VALUES (
      target_workspace_id, preset.system_key, preset.name, preset.category,
      preset.description, preset.title_pattern,
      public.polish_ledger_template_content(preset.name, preset.content_html),
      false, true, 'workspace', NULL, 0
    )
    ON CONFLICT (workspace_id, system_key) WHERE is_system = true AND system_key IS NOT NULL
    DO UPDATE SET
      name = EXCLUDED.name,
      category = EXCLUDED.category,
      description = EXCLUDED.description,
      title_pattern = EXCLUDED.title_pattern,
      content_html = EXCLUDED.content_html,
      updated_at = NOW()
    WHERE public.note_templates.is_system = true;
  END LOOP;
END;
$$;

COMMENT ON FUNCTION public.polish_ledger_template_content(TEXT, TEXT)
IS 'Applies Ledger''s structured, editor-friendly formatting to built-in note templates.';
