import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { cancelAuthSession, checkPluginChangeState, createAuthSession, createPluginIntake, createPluginTask, getPluginEditOptions, getPluginLinkedWork, getPluginSession, getWorkspaces, linkPluginWork, pollAuthSession, refreshPluginPreview, resolvePluginIdentity, revokePluginSession, searchPluginWork, unlinkPluginWork, updatePluginWorkProperty } from '../api/client';
import type { EditableProperty, FigmaSelectionContext, LinkedWorkResponse, LinkedWorkSummary, PluginAction, PluginResult, PluginTarget, PluginAppState, PluginWorkEditOptions, UserSummary, Workspace } from '../types';
import { buildNodeReferenceCache, parseNodeReferenceCache } from '../node-cache';
import './styles.css';

type Stored = { schemaVersion?: number; credential: string; workspaceId?: string; fileIdentities?: Record<string, string> };
const STORAGE_KEY = 'ledger-figma-plugin-session-v1';
const STORAGE_SCHEMA_VERSION = 2;
const migrateStored = (value: Stored | undefined): Stored | undefined => { if (!value?.credential || typeof value.credential !== 'string') return undefined; if (value.schemaVersion && value.schemaVersion > STORAGE_SCHEMA_VERSION) return undefined; return { ...value, schemaVersion: STORAGE_SCHEMA_VERSION, fileIdentities: value.fileIdentities && typeof value.fileIdentities === 'object' ? value.fileIdentities : {} }; };
const BASE_SCOPES = ['workspace:read', 'figma-context:read', 'external-reference:create', 'external-reference:link', 'external-reference:unlink', 'intake:create', 'task:create', 'work:search'];
const UPDATE_SCOPES: Record<EditableProperty, string> = { status: 'work:update:status', assignee: 'work:update:assignee', priority: 'work:update:priority', project: 'work:update:project', dueDate: 'work:update:due-date' };
const VERSION_SCOPES = { check: 'external-reference:check-version', refresh: 'external-reference:refresh-preview' };
const SCOPES = BASE_SCOPES;
const supported = new Set(['FRAME', 'SECTION', 'COMPONENT', 'COMPONENT_SET', 'GROUP', 'PAGE']);
const randomId = () => { const nativeCrypto = typeof window !== 'undefined' ? window.crypto : undefined; return typeof nativeCrypto?.randomUUID === 'function' ? nativeCrypto.randomUUID() : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`; };
const crypto = { randomUUID: randomId };
const post = (message: unknown) => window.parent.postMessage({ pluginMessage: message }, '*');
const storageRequest = <T,>(type: 'storage-get' | 'storage-set' | 'storage-delete', key: string, value?: unknown) => new Promise<T>((resolve) => { const requestId = randomId(); let timer = 0; const finish = (result: T) => { window.clearTimeout(timer); window.removeEventListener('message', handler); resolve(result); }; const handler = (event: MessageEvent) => { const message = event.data?.pluginMessage; if (message?.type !== 'storage-response' || message.requestId !== requestId) return; finish((message.value ?? message.ok) as T); }; window.addEventListener('message', handler); timer = window.setTimeout(() => finish(undefined as T), 5000); try { post({ type, requestId, key, value }); } catch { finish(undefined as T); } });
const nodeDataRequest = (nodeId: string) => new Promise<unknown>((resolve) => { const requestId = randomId(); const handler = (event: MessageEvent) => { const message = event.data?.pluginMessage; if (message?.type !== 'node-reference-response' || message.requestId !== requestId) return; window.removeEventListener('message', handler); resolve(message.value); }; window.addEventListener('message', handler); post({ type: 'node-reference-get', nodeId, requestId }); });
const safeUrl = (value: string) => { try { const url = new URL(value); const trustedWeb = ['ledgerworkspace.com', 'www.ledgerworkspace.com', 'api.ledgerworkspace.com', 'localhost', '127.0.0.1'].includes(url.hostname); const trustedDesktop = url.protocol === 'ledger:' && ['task', 'project', 'note', 'inbox'].includes(url.hostname) && /^[0-9a-f-]{16,}$/i.test(url.pathname.slice(1)); return (['https:', 'http:'].includes(url.protocol) && trustedWeb) || trustedDesktop; } catch { return false; } };
const openExternal = (url?: string) => { if (!url || !safeUrl(url)) return; try { const opened = window.open(url, '_blank', 'noopener,noreferrer'); if (!opened) post({ type: 'open-external', url }); } catch { post({ type: 'open-external', url }); } };
let propertyTargetCache: LinkedWorkSummary | null = null;
let propertyOptionsCache: PluginWorkEditOptions | null = null;
let propertySaveCache: ((row: LinkedWorkSummary, property: EditableProperty, value: string | null) => Promise<void>) | null = null;
let propertyBackCache: () => void = () => undefined;
let propertyErrorCache = '';
let propertyBusyCache: EditableProperty | null = null;

function App() {
  const [state, setState] = useState<PluginAppState>('loading'); const [credential, setCredential] = useState<string | null>(null); const [user, setUser] = useState<UserSummary | null>(null); const [grantedScopes, setGrantedScopes] = useState<string[]>([]); const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspaceId, setWorkspaceId] = useState<string | null>(null); const [selection, setSelection] = useState<FigmaSelectionContext | null>(null); const [auth, setAuth] = useState<{ sessionId: string; code: string; pollSecret: string; url: string } | null>(null); const [authScopes, setAuthScopes] = useState<string[] | undefined>(); const [error, setError] = useState(''); const [action, setAction] = useState<PluginAction | null>(null); const [result, setResult] = useState<PluginResult | null>(null); const [figmaUrl, setFigmaUrl] = useState(''); const [identityUrl, setIdentityUrl] = useState(''); const [title, setTitle] = useState(''); const [details, setDetails] = useState(''); const [projectId, setProjectId] = useState(''); const [assigneeId, setAssigneeId] = useState(''); const [dueDate, setDueDate] = useState(''); const [targets, setTargets] = useState<PluginTarget[]>([]); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false); const [linked, setLinked] = useState<LinkedWorkSummary[]>([]); const [linkedLoading, setLinkedLoading] = useState(false); const [linkedError, setLinkedError] = useState(''); const [identityRequired, setIdentityRequired] = useState(false); const [menuTarget, setMenuTarget] = useState<string | null>(null); const [confirmTarget, setConfirmTarget] = useState<LinkedWorkSummary | null>(null); const [pendingUnlink, setPendingUnlink] = useState<LinkedWorkSummary | null>(null); const linkedRequest = useRef(0);
  const [detailTarget, setDetailTarget] = useState<LinkedWorkSummary | null>(null); const [editOptions, setEditOptions] = useState<PluginWorkEditOptions | null>(null); const [optionsLoading, setOptionsLoading] = useState(false); const [propertyBusy, setPropertyBusy] = useState<EditableProperty | null>(null); const [propertyError, setPropertyError] = useState(''); const [pendingProperty, setPendingProperty] = useState<{ target: LinkedWorkSummary; property: EditableProperty; value: string | null } | null>(null); const [changeState, setChangeState] = useState<string>('unknown'); const [previewBusy, setPreviewBusy] = useState(false); const [previewError, setPreviewError] = useState(''); const [pendingPreviewRefresh, setPendingPreviewRefresh] = useState(false);
  const selectedWorkspace = useMemo(() => workspaces.find((row) => row.id === workspaceId) ?? null, [workspaces, workspaceId]); const selectedNode = selection?.nodes.length === 1 && supported.has(selection.nodes[0].type.toUpperCase()) ? selection.nodes[0] : null;
  const selectionPayload = () => ({ node_id: selectedNode?.id, node_name: selectedNode?.name, node_type: selectedNode?.type, page_name: selection?.pageName });
  const canonicalCandidate = () => figmaUrl.trim() || identityUrl.trim() || (selection?.fileKey && selectedNode ? `https://www.figma.com/design/${encodeURIComponent(selection.fileKey)}?node-id=${encodeURIComponent(selectedNode.id)}` : '');
  const remember = (referenceId: string | null, rows: LinkedWorkSummary[]) => { if (!selectedNode || !workspaceId) return; post({ type: 'node-reference-set', nodeId: selectedNode.id, value: JSON.stringify(buildNodeReferenceCache(workspaceId, referenceId || '', rows)) }); };
  const reconcileLocalData = async (rows: LinkedWorkSummary[], referenceId: string | null) => { if (!selectedNode) return; parseNodeReferenceCache(String(await nodeDataRequest(selectedNode.id) || '')); remember(referenceId, rows); };
  const loadLinkedWork = async (options: { preserve?: boolean } = {}) => { if (!credential || !workspaceId || !selectedNode) { setLinked([]); setChangeState('unknown'); setIdentityRequired(false); return; } const candidate = canonicalCandidate(); if (!candidate) { setLinked([]); setChangeState('unknown'); setIdentityRequired(true); return; } const requestId = ++linkedRequest.current; setLinkedLoading(true); setLinkedError(''); setPreviewError(''); try { const resolved = await resolvePluginIdentity(credential, workspaceId, candidate, selectionPayload()); if (requestId !== linkedRequest.current) return; const response: LinkedWorkResponse = await getPluginLinkedWork(credential, workspaceId, { figma_url: resolved.canonical_url, selection: selectionPayload() }); if (requestId !== linkedRequest.current) return; setIdentityRequired(false); setLinked(response.linked_work); setChangeState(response.change_state?.change_state || 'unknown'); await reconcileLocalData(response.linked_work, response.external_reference_id); if (grantedScopes.includes(VERSION_SCOPES.check)) { const checked = await checkPluginChangeState(credential, workspaceId, { figma_url: resolved.canonical_url, selection: selectionPayload() }); if (requestId === linkedRequest.current) setChangeState(checked.change_state); } } catch (err) { if (requestId !== linkedRequest.current) return; if (!options.preserve) setLinked([]); setLinkedError(err instanceof Error ? err.message : 'Ledger couldn’t refresh linked work.'); } finally { if (requestId === linkedRequest.current) setLinkedLoading(false); } };
  const hydrate = async () => { const raw = migrateStored(await storageRequest<Stored | undefined>('storage-get', STORAGE_KEY)); if (!raw?.credential) { setState('signed_out'); return; } await storageRequest('storage-set', STORAGE_KEY, raw); try { const session = await getPluginSession(raw.credential); const rows = await getWorkspaces(raw.credential); setCredential(raw.credential); setGrantedScopes(session.scopes || []); setUser(session.user); setWorkspaces(rows); const selected = rows.find((row) => row.id === raw.workspaceId); setWorkspaceId(selected?.id ?? null); setState(selected ? 'ready' : 'workspace_required'); } catch (err) { await storageRequest('storage-delete', STORAGE_KEY); setCredential(null); setState('expired'); setError(err instanceof Error ? err.message : 'Your Ledger session expired.'); } };
  useEffect(() => { void hydrate(); const handler = (event: MessageEvent) => { if (event.data?.pluginMessage?.type === 'selection-context') { linkedRequest.current += 1; setSelection(event.data.pluginMessage.context as FigmaSelectionContext); setIdentityUrl(''); setFigmaUrl(''); setLinked([]); setChangeState('unknown'); setPreviewError(''); setPendingPreviewRefresh(false); setLinkedError(''); setIdentityRequired(false); setMenuTarget(null); setConfirmTarget(null); setDetailTarget(null); setEditOptions(null); setPendingProperty(null); } }; window.addEventListener('message', handler); post({ type: 'request-selection' }); return () => window.removeEventListener('message', handler); }, []);
  useEffect(() => { if (state === 'ready' && credential && workspaceId && selectedNode) void loadLinkedWork(); else { setLinked([]); setLinkedLoading(false); } }, [state, credential, workspaceId, selection?.nodes.map((node) => node.id).join(','), identityUrl]);
  useEffect(() => { if (state === 'ready' && pendingUnlink && credential) { const next = pendingUnlink; setPendingUnlink(null); void unlink(next); } }, [state, credential, grantedScopes.join(',')]);
  useEffect(() => { if (state === 'ready' && pendingProperty && credential && grantedScopes.includes(UPDATE_SCOPES[pendingProperty.property])) { const next = pendingProperty; setPendingProperty(null); void saveProperty(next.target, next.property, next.value); } }, [state, credential, grantedScopes.join(','), pendingProperty]);
  useEffect(() => { if (state === 'ready' && pendingPreviewRefresh && credential && grantedScopes.includes(VERSION_SCOPES.refresh)) { setPendingPreviewRefresh(false); void refreshPreview(); } }, [state, credential, grantedScopes.join(','), pendingPreviewRefresh]);
  useEffect(() => { propertyTargetCache = detailTarget; propertyOptionsCache = editOptions; propertySaveCache = saveProperty; propertyBackCache = () => { setDetailTarget(null); setEditOptions(null); setAction(null); }; propertyErrorCache = propertyError; propertyBusyCache = propertyBusy; if (detailTarget && action !== 'property') setAction('property'); }, [detailTarget, editOptions, action, propertyError, propertyBusy]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') { setMenuTarget(null); setConfirmTarget(null); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  const beginAuth = async (scopes = SCOPES) => { setState('authorizing'); setError(''); setAuthScopes(scopes); try { const session = await createAuthSession(randomId(), scopes); setAuth({ sessionId: session.session_id, code: session.verification_code, pollSecret: session.poll_secret, url: session.authorization_url }); openExternal(session.authorization_url); const started = Date.now(); const timer = window.setInterval(async () => { if (Date.now() - started > 600000) { clearInterval(timer); setState('signed_out'); setError('Authorization expired.'); return; } try { const polled = await pollAuthSession(session.session_id, session.poll_secret); if (polled.status === 'approved' && polled.credential) { clearInterval(timer); await storageRequest('storage-set', STORAGE_KEY, { schemaVersion: STORAGE_SCHEMA_VERSION, credential: polled.credential, workspaceId }); setAuth(null); setAuthScopes(undefined); await hydrate(); } else if (polled.status === 'expired' || polled.status === 'cancelled') { clearInterval(timer); setState('signed_out'); } } catch { /* continue polling */ } }, 2000); } catch (err) { setState('error'); setError(err instanceof Error ? err.message : 'Ledger is unavailable right now.'); } };
  const cancel = async () => { if (auth) await cancelAuthSession(auth.sessionId).catch(() => null); setAuth(null); setAuthScopes(undefined); setState(credential ? 'ready' : 'signed_out'); };
  const chooseWorkspace = async (id: string) => { if (!credential || !workspaces.some((row) => row.id === id)) return; setWorkspaceId(id); await storageRequest('storage-set', STORAGE_KEY, { schemaVersion: STORAGE_SCHEMA_VERSION, credential, workspaceId: id }); setState('ready'); };
  const signOut = async () => { if (credential) await revokePluginSession(credential).catch(() => null); await storageRequest('storage-delete', STORAGE_KEY); setCredential(null); setUser(null); setWorkspaceId(null); setState('signed_out'); };
  const startAction = (next: PluginAction) => { if (!selectedNode) return; setAction(next); setResult(null); setError(''); setTitle(selectedNode.name || (next === 'intake' ? 'Figma design' : 'New task')); setDetails(''); setQuery(''); setTargets([]); };
  const submit = async () => { if (!credential || !workspaceId || !selectedNode || !action || busy) return; setBusy(true); setError(''); try { let canonical = canonicalCandidate(); if (canonical) canonical = (await resolvePluginIdentity(credential, workspaceId, canonical, selectionPayload())).canonical_url; else throw new Error('Paste a link to this Figma file before sending it to Ledger.'); const body = { figma_url: canonical, selection: selectionPayload(), ...(action === 'intake' ? { title, details } : { title, project_id: projectId || undefined, assignee_id: assigneeId || undefined, due_date: dueDate || undefined }) }; const key = crypto.randomUUID(); const created = action === 'intake' ? await createPluginIntake(credential, workspaceId, body, key) : await createPluginTask(credential, workspaceId, body, key); setResult(created); setAction(null); setIdentityUrl(canonical); } catch (err) { const status = (err as Error & { status?: number }).status; if (status === 403 && authScopes?.length !== SCOPES.length) await beginAuth(SCOPES); else setError(err instanceof Error ? err.message : 'Ledger couldn’t complete this action.'); } finally { setBusy(false); } };
  const search = async (value: string) => { setQuery(value); if (!credential || !workspaceId || value.trim().length < 2) { setTargets([]); return; } try { setTargets(await searchPluginWork(credential, workspaceId, value.trim())); } catch { setError('Ledger couldn’t search this workspace.'); } };
  const link = async (target: PluginTarget) => { if (!credential || !workspaceId || !selectedNode || busy) return; setBusy(true); try { let canonical = canonicalCandidate(); if (!canonical) throw new Error('Paste a link to this Figma file before linking.'); canonical = (await resolvePluginIdentity(credential, workspaceId, canonical, selectionPayload())).canonical_url; const linkedResult = await linkPluginWork(credential, workspaceId, { figma_url: canonical, selection: selectionPayload(), target_type: target.type, target_id: target.id }); setResult(linkedResult); setAction(null); setIdentityUrl(canonical); } catch (err) { const status = (err as Error & { status?: number }).status; if (status === 403) await beginAuth(SCOPES); else setError(err instanceof Error ? err.message : 'Ledger couldn’t link this design.'); } finally { setBusy(false); } };
  const unlink = async (row: LinkedWorkSummary) => { if (!credential || !workspaceId || !selectedNode || busy) return; setBusy(true); setMenuTarget(null); try { const candidate = canonicalCandidate(); if (!candidate) throw new Error('File identity is required.'); const canonical = (await resolvePluginIdentity(credential, workspaceId, candidate, selectionPayload())).canonical_url; await unlinkPluginWork(credential, workspaceId, { figma_url: canonical, selection: selectionPayload(), target_type: row.type, target_id: row.id }); setConfirmTarget(null); await loadLinkedWork({ preserve: true }); } catch (err) { const status = (err as Error & { status?: number }).status; if (status === 403 && !grantedScopes.includes('external-reference:unlink')) { setPendingUnlink(row); await beginAuth([...new Set([...grantedScopes, 'external-reference:unlink'])]); } else setLinkedError(err instanceof Error ? err.message : 'Ledger couldn’t unlink this design.'); } finally { setBusy(false); } };
  const copyLink = async (row: LinkedWorkSummary) => { if (!safeUrl(row.ledgerUrl)) return; try { await navigator.clipboard.writeText(row.ledgerUrl); } catch { setLinkedError('Ledger link could not be copied.'); } setMenuTarget(null); };
  const openProperties = async (row: LinkedWorkSummary) => { setMenuTarget(null); setDetailTarget(row); setEditOptions(null); setPropertyError(''); setOptionsLoading(true); try { if (!credential || !workspaceId) return; setEditOptions(await getPluginEditOptions(credential, workspaceId, row.type, row.id)); } catch (err) { setPropertyError(err instanceof Error ? err.message : 'Ledger couldn’t load edit options.'); } finally { setOptionsLoading(false); } };
  const saveProperty = async (row: LinkedWorkSummary, property: EditableProperty, value: string | null) => { if (!credential || !workspaceId || propertyBusy) return; setPropertyBusy(property); setPropertyError(''); try { const canonical = await resolvePluginIdentity(credential, workspaceId, canonicalCandidate(), selectionPayload()); await updatePluginWorkProperty(credential, workspaceId, row.type, row.id, { figma_url: canonical.canonical_url, selection: selectionPayload(), property, value, expected_updated_at: row.updatedAt }, crypto.randomUUID()); setDetailTarget(null); setEditOptions(null); await loadLinkedWork({ preserve: true }); } catch (err) { const status = (err as Error & { status?: number }).status; if (status === 403 && !grantedScopes.includes(UPDATE_SCOPES[property])) { setPendingProperty({ target: row, property, value }); await beginAuth([...new Set([...grantedScopes, UPDATE_SCOPES[property]])]); } else if (status === 409) setPropertyError('This item changed in Ledger. Refresh it before updating this property.'); else setPropertyError(err instanceof Error ? err.message : 'Ledger couldn’t update this property.'); } finally { setPropertyBusy(null); } };
  const refreshPreview = async () => { if (!credential || !workspaceId || !selectedNode || previewBusy) return; setPreviewBusy(true); setPreviewError(''); try { const canonical = await resolvePluginIdentity(credential, workspaceId, canonicalCandidate(), selectionPayload()); const refreshed = await refreshPluginPreview(credential, workspaceId, { figma_url: canonical.canonical_url, selection: selectionPayload(), target_type: linked[0]?.type, target_id: linked[0]?.id }, crypto.randomUUID()); if (refreshed.error) throw new Error(refreshed.error); setChangeState('current'); await loadLinkedWork({ preserve: true }); } catch (err) { const status = (err as Error & { status?: number }).status; if (status === 403 && !grantedScopes.includes(VERSION_SCOPES.refresh)) { setPendingPreviewRefresh(true); await beginAuth([...new Set([...grantedScopes, VERSION_SCOPES.refresh])]); } else setPreviewError(err instanceof Error ? err.message : 'Ledger couldn’t refresh this preview.'); } finally { setPreviewBusy(false); } };
  const ready = <><header><div className="brand"><span className="logo">L</span><span>Ledger Design</span></div>{user && <button className="account" onClick={() => void signOut()}>Sign out</button>}</header>{selectedWorkspace && <section className="screen ready"><button className="switcher" onClick={() => setState('workspace_required')}>{selectedWorkspace.name}<span>⌄</span></button><SelectionScreen selection={selection} node={selectedNode} onAction={startAction} />{selectedNode && <PreviewState changeState={changeState} busy={previewBusy} error={previewError} onRefresh={() => void refreshPreview()} />}{selectedNode && <LinkedWorkSection rows={linked} loading={linkedLoading} error={linkedError} identityRequired={identityRequired} identityUrl={identityUrl} setIdentityUrl={setIdentityUrl} onIdentity={() => void loadLinkedWork()} onRefresh={() => void loadLinkedWork({ preserve: true })} menuTarget={menuTarget} setMenuTarget={setMenuTarget} onOpen={openExternal} onCopy={copyLink} onRefreshRow={() => void loadLinkedWork({ preserve: true })} onUnlink={setConfirmTarget} onEdit={openProperties} />}</section>}</>;
  const propertyAuthorization = authScopes?.some((scope) => scope.startsWith('work:update:'));
  return <div className="app">{state === 'loading' && <Status label="Loading Ledger session…" />}{state === 'signed_out' && <section className="screen"><h1>Connect Ledger</h1><p>Send selected Figma designs into your Ledger workspace.</p><button className="primary" onClick={() => void beginAuth()}>Connect Ledger</button></section>}{state === 'authorizing' && <section className="screen"><h1>{propertyAuthorization ? 'Allow property updates?' : 'Allow Ledger to create and link work?'}</h1><p>{propertyAuthorization ? 'Ledger needs permission to update linked work from Figma.' : 'The plugin needs permission to create Intake items, tasks, and design links in your selected workspace.'}</p>{auth && <><div className="code">{auth.code}</div><button className="secondary" onClick={() => openExternal(auth.url)}>Open Ledger again</button><button className="link" onClick={() => void cancel()}>Cancel</button></>}</section>}{state === 'workspace_required' && <WorkspaceScreen workspaces={workspaces} onSelect={chooseWorkspace} />}{state === 'ready' && ready}{(state === 'expired' || state === 'offline' || state === 'error') && <section className="screen"><h1>{state === 'expired' ? 'Your Ledger session expired.' : 'Ledger is unavailable right now.'}</h1><p>{error || 'Check your connection and try again.'}</p><button className="primary" onClick={() => void hydrate()}>Retry</button></section>}{action && selectedNode && <ActionForm action={action} figmaUrl={figmaUrl} setFigmaUrl={setFigmaUrl} title={title} setTitle={setTitle} details={details} setDetails={setDetails} projectId={projectId} setProjectId={setProjectId} assigneeId={assigneeId} setAssigneeId={setAssigneeId} dueDate={dueDate} setDueDate={setDueDate} query={query} onSearch={search} targets={targets} onLink={link} onSubmit={() => void submit()} onBack={() => setAction(null)} busy={busy} error={error} fileKeyAvailable={Boolean(selection?.fileKeyAvailable)} />}{result && <Success result={result} onDone={() => { setResult(null); void loadLinkedWork({ preserve: true }); }} />}{confirmTarget && <ConfirmUnlink row={confirmTarget} busy={busy} onCancel={() => setConfirmTarget(null)} onConfirm={() => void unlink(confirmTarget)} />}</div>;
}

const Status = ({ label }: { label: string }) => <div className="status" role="status"><span className="spinner" />{label}</div>;
const WorkspaceScreen = ({ workspaces, onSelect }: { workspaces: Workspace[]; onSelect: (id: string) => void }) => <section className="screen"><h1>Choose a workspace</h1><p>Only workspaces you can access are shown.</p><div className="workspace-list">{workspaces.map((workspace) => <button className="workspace" key={workspace.id} onClick={() => onSelect(workspace.id)}><span className="avatar">{workspace.name.slice(0, 1).toUpperCase()}</span><span><strong>{workspace.name}</strong><small>{workspace.is_personal ? 'Personal' : 'Team'}</small></span><span>›</span></button>)}</div></section>;
const SelectionScreen = ({ selection, node, onAction }: { selection: FigmaSelectionContext | null; node: { id: string; name: string; type: string } | null; onAction: (action: PluginAction) => void }) => { if (!selection?.nodes.length) return <div className="empty"><h2>Nothing selected</h2><p>Select a frame, section, or component in Figma.</p></div>; if (selection.nodes.length !== 1 || !node) return <div className="empty"><h2>Select one layer</h2><p>Choose one frame, section, or component to view Ledger work.</p></div>; return <div className="selection"><p className="eyebrow">Selected</p><h2>{node.name}</h2><p className="meta">{node.type.replace(/_/g, ' ')} · {selection.pageName}</p><div className="actions"><button className="primary" onClick={() => onAction('intake')}>Send to Intake</button><div><button className="secondary" onClick={() => onAction('task')}>Create task</button><button className="secondary" onClick={() => onAction('link')}>Link existing</button></div></div></div>; };
const PreviewState = ({ changeState, busy, error, onRefresh }: { changeState: string; busy: boolean; error: string; onRefresh: () => void }) => { if (changeState === 'unknown') return null; const updated = changeState === 'updated'; const unavailable = changeState === 'unavailable'; return <section className="preview-state" aria-live="polite"><div><strong>Ledger preview</strong><small>{updated ? 'Design updated since capture' : unavailable ? 'Source unavailable · saved preview preserved' : changeState === 'checking' ? 'Checking for updates…' : 'Current saved preview'}</small></div><button className="secondary" onClick={onRefresh} disabled={busy || unavailable}>{busy ? 'Refreshing…' : updated ? 'Refresh Ledger preview' : 'Check again'}</button>{error && <p className="error" role="alert">{error}</p>}</section>; };
const LinkedWorkSection = (p: { rows: LinkedWorkSummary[]; loading: boolean; error: string; identityRequired: boolean; identityUrl: string; setIdentityUrl: (value: string) => void; onIdentity: () => void; onRefresh: () => void; menuTarget: string | null; setMenuTarget: (value: string | null) => void; onOpen: (url?: string) => void; onCopy: (row: LinkedWorkSummary) => void; onRefreshRow: () => void; onUnlink: (row: LinkedWorkSummary) => void; onEdit: (row: LinkedWorkSummary) => void }) => <section className="linked" aria-labelledby="linked-work-title"><div className="linked-heading"><span><strong id="linked-work-title">Linked work</strong>{!p.loading && <small>{p.rows.length}</small>}</span><button className="icon-button" aria-label="Refresh linked work" onClick={p.onRefresh} disabled={p.loading}>↻</button></div>{p.identityRequired ? <div className="identity"><p>Connect this Figma file to view linked work.</p><input aria-label="Figma file or frame link" value={p.identityUrl} onChange={(event) => p.setIdentityUrl(event.target.value)} placeholder="https://figma.com/design/..." /><button className="secondary" onClick={p.onIdentity} disabled={!p.identityUrl.trim()}>Add Figma link</button></div> : p.loading && !p.rows.length ? <div className="linked-skeleton" role="status">Loading linked work…</div> : p.rows.length ? <div className="linked-list" role="list">{p.rows.map((row) => <LinkedRow key={`${row.type}:${row.id}`} row={row} open={p.onOpen} copy={p.onCopy} refresh={p.onRefreshRow} unlink={p.onUnlink} edit={p.onEdit} menuTarget={p.menuTarget} setMenuTarget={p.setMenuTarget} />)}</div> : <p className="linked-empty">No linked work</p>}{p.error && <p className="linked-error" role="alert">{p.error}</p>}</section>;
const LinkedRow = (p: { row: LinkedWorkSummary; open: (url?: string) => void; copy: (row: LinkedWorkSummary) => void; refresh: () => void; unlink: (row: LinkedWorkSummary) => void; edit: (row: LinkedWorkSummary) => void; menuTarget: string | null; setMenuTarget: (value: string | null) => void }) => { const key = `${p.row.type}:${p.row.id}`; const openUrl = p.row.openUrl || p.row.ledgerUrl; const metadata = [typeLabel(p.row.type), p.row.status, p.row.assignee?.name, p.row.projectName, p.row.dueDate].filter(Boolean).join(' · '); return <div className="linked-row" role="listitem" tabIndex={0} onClick={() => p.open(openUrl)} onKeyDown={(event) => { if (event.key === 'Enter') p.open(openUrl); }}><span className="linked-copy"><strong>{p.row.title}</strong><small>{metadata}</small></span><span className="row-menu-wrap"><button className="overflow" aria-label={`Actions for ${p.row.title}`} onClick={(event) => { event.stopPropagation(); p.setMenuTarget(p.menuTarget === key ? null : key); }}>•••</button>{p.menuTarget === key && <div className="row-menu" role="menu"><button onClick={() => p.open(openUrl)}>Open in Ledger</button><button onClick={() => p.copy(p.row)}>Copy Ledger link</button>{p.row.editCapabilities?.canEdit && <button onClick={() => p.edit(p.row)}>Edit properties</button>}<button onClick={p.refresh}>Refresh</button>{p.row.canUnlink ? <button className="danger-action" onClick={() => p.unlink(p.row)}>Unlink design</button> : <span className="menu-note">You can view this item, but you don’t have permission to unlink it.</span>}</div>}</span></div>; };
const typeLabel = (type: string) => ({ task: 'Task', project: 'Project', note: 'Note', meetingNote: 'Meeting note', intake: 'Intake' } as Record<string, string>)[type] || 'Ledger item';
const ConfirmUnlink = ({ row, busy, onCancel, onConfirm }: { row: LinkedWorkSummary; busy: boolean; onCancel: () => void; onConfirm: () => void }) => <div className="confirm-backdrop" role="presentation"><section className="confirm" role="dialog" aria-modal="true" aria-labelledby="unlink-title"><h2 id="unlink-title">Unlink this design?</h2><p>The design will be removed from this Ledger item unless it is also linked through another source.</p><div><button className="secondary" onClick={onCancel} disabled={busy}>Cancel</button><button className="primary" onClick={onConfirm} disabled={busy}>{busy ? 'Unlinking…' : 'Unlink'}</button></div></section></div>;
const ActionForm = (p: any) => p.action === 'property' ? <PropertyEditor row={propertyTargetCache} options={propertyOptionsCache} error={propertyErrorCache} busy={propertyBusyCache} onBack={() => propertyBackCache?.()} onSave={propertySaveCache} /> : <section className="modal" aria-label={`${p.action} form`}><button className="back" onClick={p.onBack}>‹ Back</button><h1>{p.action === 'intake' ? 'Send to Intake' : p.action === 'task' ? 'Create task' : 'Link existing work'}</h1>{p.action === 'link' ? <><label>Search tasks, projects, notes<input autoFocus value={p.query} onChange={(event) => void p.onSearch(event.target.value)} placeholder="Search work…" /></label><div className="results">{p.targets.map((target: PluginTarget) => <button className="result" key={`${target.type}:${target.id}`} onClick={() => void p.onLink(target)}><strong>{target.title}</strong><small>{target.subtitle || target.type} {target.status ? `· ${target.status}` : ''}</small></button>)}</div></> : <>{!p.fileKeyAvailable && <label>Figma link<input value={p.figmaUrl} onChange={(event) => p.setFigmaUrl(event.target.value)} placeholder="https://figma.com/design/..." required /></label>}<label>Title<input autoFocus value={p.title} onChange={(event) => p.setTitle(event.target.value)} /></label>{p.action === 'intake' ? <label>Details<textarea value={p.details} onChange={(event) => p.setDetails(event.target.value)} placeholder="Optional context…" /></label> : <><label>Project<input value={p.projectId} onChange={(event) => p.setProjectId(event.target.value)} placeholder="Optional project ID" /></label><label>Assignee<input value={p.assigneeId} onChange={(event) => p.setAssigneeId(event.target.value)} placeholder="Optional assignee ID" /></label><label>Due date<input type="date" value={p.dueDate} onChange={(event) => p.setDueDate(event.target.value)} /></label></>}<button className="primary wide" disabled={p.busy || (!p.fileKeyAvailable && !p.figmaUrl.trim())} onClick={p.onSubmit}>{p.busy ? 'Sending…' : p.action === 'intake' ? 'Send to Intake' : 'Create task'}</button></>}{p.error && <p className="error" role="alert">{p.error}</p>}</section>;
const PropertyEditor = ({ row, options, error, busy, onBack, onSave }: { row: LinkedWorkSummary | null; options: PluginWorkEditOptions | null; error: string; busy: EditableProperty | null; onBack: () => void; onSave: ((row: LinkedWorkSummary, property: EditableProperty, value: string | null) => Promise<void>) | null }) => <section className="modal" aria-label="Edit properties"><button className="back" onClick={onBack}>‹ Linked work</button>{row && <><p className="eyebrow">{typeLabel(row.type)}</p><h1>{row.title}</h1>{!options ? <div className="linked-skeleton" role="status">Loading edit options…</div> : <div className="property-list">{options.capabilities.editableProperties.includes('status') && <PropertyPicker label="Status" value={row.status || ''} options={options.statuses || []} busy={busy === 'status'} onChange={(value) => void onSave?.(row, 'status', value)} />}{options.capabilities.editableProperties.includes('assignee') && <PropertyPicker label="Assignee" value={row.assignee?.id || ''} options={[{ id: '', name: 'Unassigned' }, ...(options.assignees || [])]} busy={busy === 'assignee'} onChange={(value) => void onSave?.(row, 'assignee', value || null)} />}{options.capabilities.editableProperties.includes('priority') && <PropertyPicker label="Priority" value={row.priority || ''} options={[{ id: '', name: 'No priority' }, ...(options.priorities || [])]} busy={busy === 'priority'} onChange={(value) => void onSave?.(row, 'priority', value || null)} />}{options.capabilities.editableProperties.includes('project') && <PropertyPicker label="Project" value={row.projectId || ''} options={[{ id: '', name: 'No project' }, ...(options.projects || [])]} busy={busy === 'project'} onChange={(value) => void onSave?.(row, 'project', value || null)} />}{options.capabilities.editableProperties.includes('dueDate') && <label className="property-row"><span>Due date</span><input type="date" defaultValue={row.dueDate || ''} disabled={Boolean(busy)} onChange={(event) => void onSave?.(row, 'dueDate', event.target.value || null)} /></label>}</div>}{error && <p className="error" role="alert">{error}</p>}{row.ledgerUrl && <button className="secondary wide" onClick={() => openExternal(row.openUrl || row.ledgerUrl)}>Open in Ledger</button>}</>}</section>;
const PropertyPicker = ({ label, value, options, busy, onChange }: { label: string; value: string; options: Array<{ id: string; name: string }>; busy: boolean; onChange: (value: string) => void }) => <label className="property-row"><span>{label}</span><select value={value} disabled={busy} onChange={(event) => onChange(event.target.value)}><option value="" disabled={label !== 'Assignee' && label !== 'Priority' && label !== 'Project'}>{label === 'Status' ? 'Select status' : label === 'Assignee' ? 'Unassigned' : label === 'Priority' ? 'No priority' : 'No project'}</option>{options.filter((option) => option.id !== '').map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>;
const Success = ({ result, onDone }: { result: PluginResult; onDone: () => void }) => <section className="modal success"><p className="eyebrow">{result.already_linked ? 'Already linked' : result.target.type === 'intake' ? 'Sent to Intake' : result.target.type === 'task' ? 'Task created' : 'Design linked'}</p><h1>{result.target.title}</h1><p>{result.partial ? 'The work was saved, but Ledger couldn’t generate its preview.' : 'Ledger Design'}</p>{(result.target.open_url || result.target.url) && <button className="primary wide" onClick={() => openExternal(result.target.open_url || result.target.url)}>Open in Ledger</button>}<button className="link" onClick={onDone}>Done</button></section>;
const mount = () => {
  const rootElement = document.getElementById('root') || (() => {
    const element = document.createElement('div');
    element.id = 'root';
    document.body?.appendChild(element);
    return element;
  })();
  const mountWindow = window as typeof window & { __ledgerPluginRoot?: ReturnType<typeof createRoot> };
  if (mountWindow.__ledgerPluginRoot) {
    mountWindow.__ledgerPluginRoot.render(<App />);
    return;
  }
  mountWindow.__ledgerPluginRoot = createRoot(rootElement);
  mountWindow.__ledgerPluginRoot.render(<App />);
};

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount, { once: true });
else mount();
