import { Check } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useAppleCalendar, type AppleCalendar } from './appleCalendar';
import { useAppleReminders, type AppleReminderList } from './appleReminders';

type Props = { userId?: string; compact?: boolean; onChanged?: () => void };

export const AppleCalendarConnection = ({ userId, onChanged }: Props) => {
  const range = useMemo(() => ({ start: new Date(Date.now() - 86400000), end: new Date(Date.now() + 86400000 * 90) }), []);
  const apple = useAppleCalendar(userId, range.start, range.end);
  const reminders = useAppleReminders(userId, range.start, range.end);
  const [selectionOpen, setSelectionOpen] = useState(false);
  const [draft, setDraft] = useState<AppleCalendar[]>([]);
  const [reminderSelectionOpen, setReminderSelectionOpen] = useState(false);
  const [reminderDraft, setReminderDraft] = useState<AppleReminderList[]>([]);
  const groups = useMemo(() => Object.entries(apple.calendars.reduce<Record<string, AppleCalendar[]>>((result, item) => { (result[item.sourceTitle] ??= []).push(item); return result; }, {})), [apple.calendars]);
  const reminderGroups = useMemo(() => Object.entries(reminders.lists.reduce<Record<string, AppleReminderList[]>>((result, item) => { (result[item.sourceTitle] ??= []).push(item); return result; }, {})), [reminders.lists]);
  if (!apple.supported) return null;
  const openSelection = async () => { if (!await apple.connect()) return; const calendars = await apple.refreshCalendars(); setDraft(calendars.filter((item) => item.available && item.visible)); setSelectionOpen(true); };
  const openReminderSelection = async () => {
    if (!await reminders.connect()) return;
    const lists = await reminders.refreshLists();
    setReminderDraft(lists.filter((item) => item.available && item.visible));
    setReminderSelectionOpen(true);
  };
  const permissionIssue = apple.permission === 'denied' || apple.permission === 'restricted';
  const reminderPermissionIssue = reminders.permission === 'denied' || reminders.permission === 'restricted';
  return <div>
    <div className="divide-y divide-[color:var(--ledger-border-subtle)]">
    <div className="px-4 py-2.5">
      <div className="flex flex-wrap items-center gap-3">
        <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[var(--ledger-surface-muted)]"><img src={`${import.meta.env.BASE_URL}apple.svg`} alt="" className="h-4 w-4 dark:invert" /></span>
        <div className="min-w-0 flex-1"><p className="text-[13px] font-medium text-[var(--ledger-text-primary)]">Apple Calendar <span className="ml-1 text-[11px] font-normal text-[var(--ledger-text-muted)]">{apple.connected ? 'Connected' : 'Not connected'}</span></p><p className="mt-0.5 text-[11px] leading-4 text-[var(--ledger-text-muted)]">View events from calendars available on this Mac alongside your Ledger work.</p></div>
        {apple.connected ? <div className="flex shrink-0 gap-2"><button type="button" onClick={() => { void apple.refreshCalendars().then((items) => { setDraft(items.filter((item) => item.available && item.visible)); setSelectionOpen(true); }).catch(() => undefined); }} className="h-7 rounded-md border border-[color:var(--ledger-border-subtle)] px-2.5 text-[11px] font-medium">Manage</button><button type="button" onClick={() => { if (window.confirm('Disconnect Apple Calendar from Ledger? Apple Calendar will not be changed.')) apple.disconnect(); }} className="h-7 rounded-md border border-[color:rgba(217,45,32,0.18)] px-2.5 text-[11px] font-medium text-[var(--ledger-danger)]">Disconnect</button></div> : <button type="button" onClick={() => void openSelection().catch(() => undefined)} disabled={apple.loading} className="h-7 shrink-0 rounded-md border border-[color:var(--ledger-border-subtle)] px-2.5 text-[11px] font-medium text-[var(--ledger-text-secondary)] hover:bg-[var(--ledger-surface-hover)] disabled:opacity-50">{apple.loading ? 'Connecting…' : 'Connect'}</button>}
      </div>
      {permissionIssue && <div className="mt-3 flex items-center gap-2 text-xs text-[var(--ledger-danger)]"><span>Ledger no longer has access to Apple Calendar. Allow calendar access in macOS System Settings to reconnect.</span><button type="button" onClick={() => void window.appleCalendar?.openSystemSettings()} className="shrink-0 underline">Open System Settings</button></div>}
      {apple.error && <p className="mt-2 text-xs text-[var(--ledger-danger)]">{apple.error}</p>}
      {apple.connected && <div className="mt-3 space-y-1">{apple.connectedCalendars.map((item) => <div key={item.id} className="flex items-center gap-2 text-xs text-[var(--ledger-text-secondary)]"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: item.color }} />{item.title}{item.available === false && <span className="text-[var(--ledger-danger)]">Unavailable</span>}</div>)}</div>}
    </div>
    <div className="px-4 py-2.5">
      <div className="flex flex-wrap items-center gap-3">
        <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[var(--ledger-surface-muted)]"><img src={`${import.meta.env.BASE_URL}apple.svg`} alt="" className="h-4 w-4 dark:invert" /></span>
        <div className="min-w-0 flex-1"><p className="text-[13px] font-medium text-[var(--ledger-text-primary)]">Apple Reminders <span className="ml-1 text-[11px] font-normal text-[var(--ledger-text-muted)]">{reminders.connected ? 'Connected' : 'Not connected'}</span></p><p className="mt-0.5 text-[11px] leading-4 text-[var(--ledger-text-muted)]">View dated reminders from lists available on this Mac alongside your Ledger work.</p></div>
        {reminders.connected ? <div className="flex shrink-0 gap-2"><button type="button" onClick={() => { void reminders.refreshLists().then((items) => { setReminderDraft(items.filter((item) => item.available && item.visible)); setReminderSelectionOpen(true); }).catch(() => undefined); }} className="h-7 rounded-md border border-[color:var(--ledger-border-subtle)] px-2.5 text-[11px] font-medium">Manage lists</button><button type="button" onClick={() => { if (window.confirm('Disconnect Apple Reminders from Ledger? Apple Reminders will not be changed.')) reminders.disconnect(); }} className="h-7 rounded-md border border-[color:rgba(217,45,32,0.18)] px-2.5 text-[11px] font-medium text-[var(--ledger-danger)]">Disconnect</button></div> : <button type="button" onClick={() => void openReminderSelection().catch(() => undefined)} disabled={reminders.loading} className="h-7 shrink-0 rounded-md border border-[color:var(--ledger-border-subtle)] px-2.5 text-[11px] font-medium text-[var(--ledger-text-secondary)] hover:bg-[var(--ledger-surface-hover)] disabled:opacity-50">{reminders.loading ? 'Connecting…' : 'Connect'}</button>}
      </div>
      {reminderPermissionIssue && <div className="mt-3 flex items-center gap-2 text-xs text-[var(--ledger-danger)]"><span>Ledger can’t access Apple Reminders. Allow access in macOS System Settings to reconnect.</span><button type="button" onClick={() => void window.appleReminders?.openSystemSettings()} className="shrink-0 underline">Open System Settings</button></div>}
      {reminders.error && <p className="mt-2 text-xs text-[var(--ledger-danger)]">{reminders.error}</p>}
      {reminders.connected && <div className="mt-3 space-y-1">{reminders.connectedLists.map((item) => <div key={item.id} className="flex items-center gap-2 text-xs text-[var(--ledger-text-secondary)]"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: item.color }} />{item.title}{item.available === false && <span className="text-[var(--ledger-danger)]">Unavailable</span>}</div>)}</div>}
    </div>
    </div>
    {selectionOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 p-4"><div className="w-full max-w-lg rounded-2xl border border-[color:var(--ledger-border-subtle)] bg-[var(--ledger-surface-card)] p-5 shadow-xl"><div className="flex items-start justify-between"><div><h2 className="text-base font-semibold">Select Apple calendars</h2><p className="mt-1 text-xs text-[var(--ledger-text-muted)]">Select entire calendars. Ledger will only read events from your selection.</p></div><button type="button" onClick={() => setSelectionOpen(false)} aria-label="Close">×</button></div><div className="mt-4 flex gap-2"><button type="button" className="text-xs underline" onClick={() => setDraft(apple.calendars.filter((item) => item.available))}>Select all</button><button type="button" className="text-xs underline" onClick={() => setDraft([])}>Clear selection</button></div><div className="mt-3 max-h-80 overflow-auto">{groups.map(([source, items]) => <div key={source} className="mb-4"><p className="mb-1 text-xs font-semibold text-[var(--ledger-text-muted)]">{source}</p>{items.filter((item) => item.available).map((item) => { const checked = draft.some((selected) => selected.id === item.id); return <button key={item.id} type="button" onClick={() => setDraft((current) => checked ? current.filter((selected) => selected.id !== item.id) : [...current, item])} className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left hover:bg-[var(--ledger-surface-hover)]"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: item.color }} /><span className="min-w-0 flex-1 text-sm">{item.title}</span>{!item.allowsContentModifications && <span className="text-[10px] text-[var(--ledger-text-muted)]">Read-only</span>}<span className={`flex h-4 w-4 items-center justify-center rounded border ${checked ? 'border-[var(--ledger-accent)] bg-[var(--ledger-accent)] text-white' : 'border-[var(--ledger-border-strong)]'}`}>{checked && <Check size={11} />}</span></button>; })}</div>)}</div><div className="mt-5 flex items-center justify-end gap-2"><button type="button" onClick={() => setSelectionOpen(false)} className="h-8 rounded-lg border border-[color:var(--ledger-border-subtle)] px-3 text-xs">Cancel</button><button type="button" disabled={!draft.length} onClick={() => { apple.saveSelection(draft); setSelectionOpen(false); onChanged?.(); }} className="h-8 rounded-lg bg-[var(--ledger-accent)] px-3 text-xs font-medium text-white disabled:opacity-50">Save calendars</button></div></div></div>}
    {reminderSelectionOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 p-4"><div className="w-full max-w-lg rounded-2xl border border-[color:var(--ledger-border-subtle)] bg-[var(--ledger-surface-card)] p-5 shadow-xl"><div className="flex items-start justify-between"><div><h2 className="text-base font-semibold">Select Apple reminder lists</h2><p className="mt-1 text-xs text-[var(--ledger-text-muted)]">Select entire lists. Ledger only shows reminders with a due date.</p></div><button type="button" onClick={() => setReminderSelectionOpen(false)} aria-label="Close">×</button></div><div className="mt-4 flex gap-2"><button type="button" className="text-xs underline" onClick={() => setReminderDraft(reminders.lists.filter((item) => item.available))}>Select all</button><button type="button" className="text-xs underline" onClick={() => setReminderDraft([])}>Clear selection</button></div><div className="mt-3 max-h-80 overflow-auto">{reminderGroups.map(([source, items]) => <div key={source} className="mb-4"><p className="mb-1 text-xs font-semibold text-[var(--ledger-text-muted)]">{source}</p>{items.filter((item) => item.available).map((item) => { const checked = reminderDraft.some((selected) => selected.id === item.id); return <button key={item.id} type="button" onClick={() => setReminderDraft((current) => checked ? current.filter((selected) => selected.id !== item.id) : [...current, item])} className="flex w-full items-center gap-3 rounded-lg px-2 py-2 text-left hover:bg-[var(--ledger-surface-hover)]"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: item.color }} /><span className="min-w-0 flex-1 text-sm">{item.title}</span><span className={`flex h-4 w-4 items-center justify-center rounded border ${checked ? 'border-[var(--ledger-accent)] bg-[var(--ledger-accent)] text-white' : 'border-[var(--ledger-border-strong)]'}`}>{checked && <Check size={11} />}</span></button>; })}</div>)}</div><div className="mt-5 flex items-center justify-end gap-2"><button type="button" onClick={() => setReminderSelectionOpen(false)} className="h-8 rounded-lg border border-[color:var(--ledger-border-subtle)] px-3 text-xs">Cancel</button><button type="button" disabled={!reminderDraft.length} onClick={() => { reminders.saveSelection(reminderDraft); setReminderSelectionOpen(false); onChanged?.(); }} className="h-8 rounded-lg bg-[var(--ledger-accent)] px-3 text-xs font-medium text-white disabled:opacity-50">Save lists</button></div></div></div>}
  </div>;
};
