export type MeetingAiEvalCase = { id: string; category: 'exact_meeting' | 'owner' | 'decision' | 'unresolved' | 'cross_meeting' | 'series' | 'state' | 'citation' | 'uncertainty' | 'isolation'; expected: 'answer' | 'refuse' | 'current_state' };
export const meetingAiEvalCases: MeetingAiEvalCase[] = [
  { id: 'meeting-decisions', category: 'decision', expected: 'answer' }, { id: 'meeting-owner', category: 'owner', expected: 'answer' }, { id: 'meeting-unresolved', category: 'unresolved', expected: 'answer' }, { id: 'meeting-pricing', category: 'exact_meeting', expected: 'answer' },
  { id: 'meeting-why-approach', category: 'exact_meeting', expected: 'answer' }, { id: 'meeting-citation', category: 'citation', expected: 'answer' }, { id: 'ambiguous-speaker', category: 'uncertainty', expected: 'refuse' }, { id: 'unknown-owner', category: 'uncertainty', expected: 'refuse' },
  { id: 'last-four-changes', category: 'cross_meeting', expected: 'answer' }, { id: 'series-followups', category: 'series', expected: 'answer' }, { id: 'exhibition-decisions', category: 'cross_meeting', expected: 'answer' }, { id: 'person-launch-history', category: 'cross_meeting', expected: 'answer' },
  { id: 'same-title-other-series', category: 'isolation', expected: 'refuse' }, { id: 'same-attendees-unrelated', category: 'isolation', expected: 'refuse' }, { id: 'linked-project-change', category: 'state', expected: 'current_state' }, { id: 'completed-followup', category: 'state', expected: 'current_state' },
  { id: 'open-followup', category: 'state', expected: 'current_state' }, { id: 'recap-vs-transcript', category: 'citation', expected: 'answer' }, { id: 'incorrect-human-note', category: 'uncertainty', expected: 'current_state' }, { id: 'cross-workspace', category: 'isolation', expected: 'refuse' },
  { id: 'deleted-segment', category: 'citation', expected: 'refuse' }, { id: 'missing-evidence', category: 'uncertainty', expected: 'refuse' }, { id: 'prep-open-action', category: 'series', expected: 'answer' }, { id: 'prep-no-filler', category: 'uncertainty', expected: 'refuse' },
  { id: 'balanced-grounding', category: 'citation', expected: 'answer' }, { id: 'fast-grounding', category: 'citation', expected: 'answer' }, { id: 'confirmed-identity', category: 'owner', expected: 'answer' }, { id: 'suggested-identity', category: 'uncertainty', expected: 'refuse' },
  { id: 'task-now-complete', category: 'state', expected: 'current_state' }, { id: 'project-overdue', category: 'state', expected: 'current_state' }, { id: 'unrelated-semantic-match', category: 'isolation', expected: 'refuse' }, { id: 'insufficient-context', category: 'uncertainty', expected: 'refuse' },
];

export const meetingAiEvalTrustGate = (metrics: { answerCorrectness: number; citationCorrectness: number; unsupportedClaims: number; falseSpeakerAttribution: number; staleStateClaims: number; crossWorkspaceLeakage: number; usefulUncertainty: number }) => metrics.answerCorrectness >= 0.8 && metrics.citationCorrectness >= 0.9 && metrics.unsupportedClaims === 0 && metrics.falseSpeakerAttribution === 0 && metrics.staleStateClaims === 0 && metrics.crossWorkspaceLeakage === 0 && metrics.usefulUncertainty >= 0.8;
