import { CircleAlert, Check, Loader2, ShieldCheck } from 'lucide-react';
import { useEffect, useState, type ReactNode } from 'react';
import { useApi } from '../../hooks/useApi';
import { FigmaMark } from '../Common/FigmaMark';
import { useWorkspaceContext } from '../../context/WorkspaceContext';

export type FigmaIntegrationStatus = {
  status: 'disconnected' | 'connecting' | 'connected' | 'expired' | 'revoked' | 'error';
  provider_user_id?: string | null;
  connected_account?: { name?: string | null; id?: string | null } | null;
  scopes?: string[];
  connected_by?: { name?: string | null; email?: string | null } | null;
  connected_on?: string | null;
  last_checked_at?: string | null;
  error?: string | null;
  change_detection?: { enabled?: boolean; health?: string; last_checked_at?: string | null };
  automation?: { notify_linked_work?: boolean; automatically_refresh_previews?: boolean; create_intake_on_change?: boolean };
};
type Props = { workspaceId: string | null; canManage: boolean; onBack: () => void; onStatusChange?: (status: FigmaIntegrationStatus) => void };
export const settingsIntegrationButton = 'h-8 rounded-full border border-[color:var(--ledger-border-subtle)] bg-[var(--ledger-surface-card)] px-3 text-xs font-medium text-[var(--ledger-text-secondary)] transition hover:bg-[var(--ledger-surface-hover)] disabled:opacity-50';
export const settingsIntegrationPrimary = 'h-9 rounded-full bg-[var(--ledger-accent)] px-4 text-sm font-medium text-white transition hover:bg-[var(--ledger-accent-hover)] disabled:opacity-60';
const button = settingsIntegrationButton;
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '—';

export const FigmaIntegrationPage = ({ workspaceId, canManage, onBack, onStatusChange }: Props) => {
  const api = useApi();
  const { activeWorkspace } = useWorkspaceContext();
  const [status, setStatus] = useState<FigmaIntegrationStatus>({ status: 'disconnected' });
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<'connect' | 'disconnect' | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [confirmDisconnect, setConfirmDisconnect] = useState(false);
  const [privacy, setPrivacy] = useState<{ preview_sharing_accepted?: boolean; preview_sharing_policy_version?: string }>({});
  const [confirmDataRemoval, setConfirmDataRemoval] = useState(false);
  const [dataRemovalName, setDataRemovalName] = useState('');
  const [dataRemovalBusy, setDataRemovalBusy] = useState(false);
  const [automation, setAutomation] = useState({ change_detection_enabled: true, notify_linked_work: false, automatically_refresh_previews: false, create_intake_on_change: false });
  const [automationBusy, setAutomationBusy] = useState(false);
  const refresh = async () => { if (!workspaceId) return; setLoading(true); try { const next = await api.getFigmaIntegrationStatus(workspaceId) as FigmaIntegrationStatus; setStatus(next); onStatusChange?.(next); setError(null); } catch (err) { setError(err instanceof Error ? err.message : 'Could not load Figma connection status.'); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, [workspaceId]);
  useEffect(() => { if (!workspaceId) return; void api.getFigmaPrivacySettings().then((value) => setPrivacy(value as typeof privacy)).catch(() => null); }, [workspaceId]);
  useEffect(() => { if (!workspaceId) return; void api.getFigmaAutomationSettings(workspaceId).then((value) => setAutomation((current) => ({ ...current, ...(value as typeof automation) }))).catch(() => null); }, [workspaceId]);
  useEffect(() => { if (status.status !== 'connecting') return; const timer = window.setInterval(() => { void refresh(); }, 2500); const timeout = window.setTimeout(() => { const failed = { ...status, status: 'error' as const, error: 'Authorization timed out. Try connecting again.' }; setStatus(failed); onStatusChange?.(failed); }, 5 * 60 * 1000); return () => { window.clearInterval(timer); window.clearTimeout(timeout); }; }, [status.status, workspaceId]);
  const connect = async () => { if (!workspaceId || !canManage) return; setBusy('connect'); setError(null); const connecting = { ...status, status: 'connecting' as const }; setStatus(connecting); onStatusChange?.(connecting); try { const response = await api.getFigmaInstallUrl(workspaceId) as { url: string }; if (!response.url) throw new Error('Figma authorization is unavailable.'); if (window.desktopWindow?.openExternal) await window.desktopWindow.openExternal(response.url); else window.open(response.url, '_blank', 'noopener,noreferrer'); } catch (err) { const failed = { ...status, status: 'error' as const }; setStatus(failed); onStatusChange?.(failed); setError(err instanceof Error ? err.message : 'We couldn’t open Figma authorization.'); } finally { setBusy(null); } };
  const disconnect = async () => { if (!workspaceId || !canManage) return; setBusy('disconnect'); setError(null); try { await api.disconnectFigmaIntegration(workspaceId); setConfirmDisconnect(false); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not disconnect Figma.'); } finally { setBusy(null); } };
  const acceptPrivacy = async () => { try { const value = await api.acceptFigmaPrivacySettings(); setPrivacy(value as typeof privacy); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save preview privacy settings.'); } };
  const removeStoredData = async () => { if (!activeWorkspace?.name || dataRemovalName !== activeWorkspace.name) return; setDataRemovalBusy(true); try { await api.removeFigmaWorkspaceData(dataRemovalName); setConfirmDataRemoval(false); setDataRemovalName(''); setError(null); } catch (err) { setError(err instanceof Error ? err.message : 'Ledger couldn’t remove all Figma data.'); } finally { setDataRemovalBusy(false); } };
  const updateAutomation = async (key: keyof typeof automation, value: boolean) => { if (!workspaceId || !canManage) return; if (key === 'automatically_refresh_previews' && value && !window.confirm('Ledger will replace the active saved preview when Figma reports a newer version. Continue?')) return; setAutomationBusy(true); try { const next = { ...automation, [key]: value, ...(key === 'automatically_refresh_previews' && value ? { confirm_automatic_refresh: true } : {}) }; const saved = await api.updateFigmaAutomationSettings(workspaceId, next) as typeof automation; setAutomation(saved); } catch (err) { setError(err instanceof Error ? err.message : 'Ledger couldn’t update Figma automation.'); } finally { setAutomationBusy(false); } };
  const statusLabel = status.status === 'connected' ? 'Connected' : status.status === 'expired' ? 'Needs renewal' : status.status === 'revoked' ? 'Access revoked' : status.status === 'connecting' ? 'Connecting' : status.status === 'error' ? 'Needs attention' : 'Not connected';
  const scopeLabels = (status.scopes ?? []).map((scope) => scope === 'current_user:read' ? 'View account information' : scope);
  return <section className="w-full max-w-215" aria-labelledby="settings-figma">
    <button type="button" onClick={onBack} className="mb-5 inline-flex items-center gap-1 text-xs font-medium text-[var(--ledger-text-muted)] hover:text-[var(--ledger-text-primary)]">← Integrations</button>
    <div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[var(--ledger-surface-muted)] text-[var(--ledger-text-secondary)]"><FigmaMark /></span><div><h2 id="settings-figma" className="text-2xl font-semibold tracking-tight text-[var(--ledger-text-primary)]">Figma</h2><p className="mt-1 text-[13px] leading-5 text-[var(--ledger-text-secondary)]">Attach Figma designs to tasks, projects, notes, and Intake items.</p></div></div>
    {!canManage && <p className="mt-5 flex items-center gap-2 text-xs text-[var(--ledger-danger)]" role="alert"><CircleAlert size={14} />You don’t have permission to manage workspace integrations.</p>}
    <IntegrationSection title="Connection">{loading ? <LoadingRow label="Checking Figma connection…" /> : status.status === 'disconnected' ? <div className="flex items-center justify-between gap-4"><div><p className="text-[13px] font-medium">Connect your Figma account</p><p className="mt-1 text-xs text-[var(--ledger-text-muted)]">Authorization opens securely in your browser.</p></div><button type="button" onClick={() => void connect()} disabled={!canManage || !!busy} className={settingsIntegrationPrimary}>{busy === 'connect' ? 'Opening…' : 'Connect Figma'}</button></div> : status.status === 'connecting' ? <LoadingRow label="Connecting to Figma…" detail="Complete authorization in your browser. Ledger will update automatically when you’re finished." action={<><button type="button" className={settingsIntegrationButton} onClick={() => void connect()} disabled={!!busy}>Open browser again</button><button type="button" className={settingsIntegrationButton} onClick={() => { const cancelled = { status: 'disconnected' as const }; setStatus(cancelled); onStatusChange?.(cancelled); }}>Cancel</button></>} /> : <><>{(['expired', 'revoked', 'error'] as const).includes(status.status as 'expired' | 'revoked' | 'error') && <div className="mb-4 flex items-start gap-2 text-xs text-[var(--ledger-danger)]" role="alert"><CircleAlert size={14} className="mt-0.5 shrink-0" /><span>{status.status === 'expired' ? 'Your Figma connection needs to be renewed.' : status.status === 'revoked' ? 'Figma access was revoked. Reconnect to continue using the integration.' : (status.error || 'We couldn’t check Figma right now. Try again in a moment.')}</span></div>}</><div className="divide-y divide-[color:var(--ledger-border-subtle)]"><MetaRow label="Connected account" value={status.connected_account?.name || status.connected_account?.id || status.provider_user_id || 'Figma account'} /><MetaRow label="Status" value={statusLabel} icon={status.status === 'connected' ? <Check size={14} /> : undefined} /><MetaRow label="Connected by" value={status.connected_by?.name || status.connected_by?.email || '—'} /><MetaRow label="Connected on" value={formatDate(status.connected_on)} /><MetaRow label="Last checked" value={status.last_checked_at ? formatDate(status.last_checked_at) : 'Just now'} /></div><div className="mt-4 flex gap-2"><button type="button" className={settingsIntegrationButton} onClick={() => void connect()} disabled={!canManage || !!busy}>{busy === 'connect' ? 'Opening…' : 'Reconnect'}</button><button type="button" className="h-8 rounded-full border border-[color:rgba(217,45,32,0.18)] px-3 text-xs font-medium text-[var(--ledger-danger)] hover:bg-[color:rgba(217,45,32,0.08)] disabled:opacity-50" onClick={() => setConfirmDisconnect(true)} disabled={!canManage || !!busy}>Disconnect</button></div></>}</IntegrationSection>
    <IntegrationSection title="Capabilities"><Capability title="Design previews" detail="Preview linked Figma files and frames in Ledger." /><Capability title="Open in Figma" detail="Open the original design from Ledger." /><Capability title="Manual refresh" detail="Refresh a saved preview when the design changes." /></IntegrationSection>
    <IntegrationSection title="Change detection"><MetaRow label="Status" value={status.change_detection?.health === 'active' || status.change_detection?.enabled ? 'Active' : 'Unavailable'} /><MetaRow label="Last checked" value={formatDate(status.change_detection?.last_checked_at)} /><p className="mt-2 text-xs text-[var(--ledger-text-muted)]">Ledger keeps the current saved preview until someone chooses to refresh it.</p>{canManage && <button type="button" className={`${settingsIntegrationButton} mt-3`} onClick={() => void refresh()}>Check connection</button>}</IntegrationSection>
    <IntegrationSection title="Automation"><ToggleRow label="Check linked designs for updates" detail="Use conservative change checks when a design is opened." checked={automation.change_detection_enabled} disabled={!canManage || automationBusy} onChange={(value) => void updateAutomation('change_detection_enabled', value)} /><ToggleRow label="Notify linked work when a design changes" detail="Create one restrained activity or notification for a confirmed source update." checked={automation.notify_linked_work} disabled={!canManage || automationBusy} onChange={(value) => void updateAutomation('notify_linked_work', value)} /><ToggleRow label="Automatically refresh saved previews" detail="Off by default. Replaces the active snapshot after a confirmed update." checked={automation.automatically_refresh_previews} disabled={!canManage || automationBusy} onChange={(value) => void updateAutomation('automatically_refresh_previews', value)} /><ToggleRow label="Create Intake items for design changes" detail="Off by default. Reuses the existing Figma reference when enabled." checked={automation.create_intake_on_change} disabled={!canManage || automationBusy} onChange={(value) => void updateAutomation('create_intake_on_change', value)} /></IntegrationSection>
    <IntegrationSection title="Permissions"><p className="text-xs text-[var(--ledger-text-muted)]">Ledger requests only the permissions returned by Figma for this connection.</p>{scopeLabels.length ? scopeLabels.map((scope) => <div key={scope} className="mt-3 flex items-start gap-2 text-[13px]"><ShieldCheck size={15} className="mt-0.5 text-[var(--ledger-text-muted)]" /><span>{scope}<span className="mt-0.5 block text-xs text-[var(--ledger-text-muted)]">Used to identify the connected Figma account.</span></span></div>) : <p className="mt-3 text-xs text-[var(--ledger-text-muted)]">No Figma permissions have been granted.</p>}</IntegrationSection>
    <IntegrationSection title="Activity"><p className="text-xs text-[var(--ledger-text-muted)]">Connection activity will appear here as the integration is used.</p></IntegrationSection>
    <IntegrationSection title="Data and privacy"><MetaRow label="Saved previews" value="Visible to people who can access the Ledger item." /><MetaRow label="Stored Figma data" value="Metadata, links, and preview snapshots." />{!privacy.preview_sharing_accepted && canManage ? <div className="mt-3 rounded-lg border border-[color:var(--ledger-border-subtle)] bg-[var(--ledger-surface-muted)] p-3"><p className="text-xs text-[var(--ledger-text-secondary)]">People who can access a Ledger item can view its saved Figma preview, even if they cannot open the original Figma file.</p><button type="button" className={`${settingsIntegrationButton} mt-3`} onClick={() => void acceptPrivacy()}>Allow previews</button></div> : null}<button type="button" className="mt-3 h-8 rounded-full border border-[color:rgba(217,45,32,0.18)] px-3 text-xs font-medium text-[var(--ledger-danger)] hover:bg-[color:rgba(217,45,32,0.08)] disabled:opacity-50" disabled={!canManage} onClick={() => setConfirmDataRemoval(true)}>Remove stored Figma data</button></IntegrationSection>
    {error && <p className="mt-3 text-xs text-[var(--ledger-danger)]" role="alert">{error}</p>}
    {confirmDisconnect && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 p-6" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setConfirmDisconnect(false); }}><div className="w-full max-w-sm rounded-2xl border border-[color:var(--ledger-border-subtle)] bg-[var(--ledger-surface-card)] p-5 shadow-[0_24px_70px_rgba(15,23,42,0.18)]" role="dialog" aria-modal="true" aria-labelledby="disconnect-figma-title"><h3 id="disconnect-figma-title" className="text-base font-semibold">Disconnect Figma?</h3><p className="mt-2 text-sm text-[var(--ledger-text-secondary)]">Ledger will stop accessing Figma and new design previews will no longer be available.</p><p className="mt-1 text-xs text-[var(--ledger-text-muted)]">Existing Ledger content will not be deleted.</p><div className="mt-5 flex justify-end gap-2"><button type="button" className={button} onClick={() => setConfirmDisconnect(false)}>Cancel</button><button type="button" className="h-8 rounded-full bg-[var(--ledger-danger)] px-3 text-xs font-medium text-white disabled:opacity-50" onClick={() => void disconnect()} disabled={!!busy}>{busy === 'disconnect' ? 'Disconnecting…' : 'Disconnect'}</button></div></div></div>}
    {confirmDataRemoval && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 p-6" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setConfirmDataRemoval(false); }}><div className="w-full max-w-sm rounded-2xl border border-[color:var(--ledger-border-subtle)] bg-[var(--ledger-surface-card)] p-5 shadow-[0_24px_70px_rgba(15,23,42,0.18)]" role="dialog" aria-modal="true" aria-labelledby="remove-figma-data-title"><h3 id="remove-figma-data-title" className="text-base font-semibold">Remove all stored Figma data?</h3><p className="mt-2 text-sm text-[var(--ledger-text-secondary)]">Saved previews and Figma links will be removed from this workspace. Nothing in Figma will be deleted. This cannot be undone.</p><label className="mt-4 block text-xs text-[var(--ledger-text-muted)]" htmlFor="figma-workspace-confirmation">Type {activeWorkspace?.name || 'the workspace name'} to continue</label><input id="figma-workspace-confirmation" value={dataRemovalName} onChange={(event) => setDataRemovalName(event.target.value)} className="mt-1 h-9 w-full rounded-md border border-[color:var(--ledger-border-subtle)] bg-transparent px-2 text-xs outline-none focus:border-[color:var(--ledger-border-strong)]" autoFocus /><div className="mt-5 flex justify-end gap-2"><button type="button" className={button} onClick={() => setConfirmDataRemoval(false)}>Cancel</button><button type="button" className="h-8 rounded-full bg-[var(--ledger-danger)] px-3 text-xs font-medium text-white disabled:opacity-50" disabled={dataRemovalName !== activeWorkspace?.name || dataRemovalBusy} onClick={() => void removeStoredData()}>{dataRemovalBusy ? 'Removing…' : 'Remove Figma data'}</button></div></div></div>}
  </section>;
};
export const IntegrationSection = ({ title, children }: { title: string; children: ReactNode }) => <section className="mt-8" aria-labelledby={`integration-${title.toLowerCase().replace(/\s/g, '-')}`}><h3 id={`integration-${title.toLowerCase().replace(/\s/g, '-')}`} className="text-[13px] font-semibold text-[var(--ledger-text-primary)]">{title}</h3><div className="mt-3 overflow-hidden rounded-xl border border-[color:var(--ledger-border-subtle)] bg-[var(--ledger-surface-card)] p-4">{children}</div></section>;
export const MetaRow = ({ label, value, icon }: { label: string; value: string; icon?: ReactNode }) => <div className="flex items-center justify-between gap-4 py-2.5 text-[13px]"><span className="text-[var(--ledger-text-muted)]">{label}</span><span className="flex items-center gap-1 text-right text-[var(--ledger-text-primary)]">{icon}{value}</span></div>;
export const Capability = ({ title, detail, status = 'Available' }: { title: string; detail: string; status?: string }) => <div className="flex items-start justify-between gap-3 py-2"><div><p className="text-[13px] font-medium">{title}</p><p className="mt-0.5 text-xs text-[var(--ledger-text-muted)]">{detail}</p></div><span className="shrink-0 text-[11px] text-[var(--ledger-text-muted)]">{status}</span></div>;
const ToggleRow = ({ label, detail, checked, disabled, onChange }: { label: string; detail: string; checked: boolean; disabled: boolean; onChange: (value: boolean) => void }) => <label className="flex items-start justify-between gap-4 border-b border-[color:var(--ledger-border-subtle)] py-3 last:border-b-0"><span><span className="block text-[13px] font-medium">{label}</span><span className="mt-0.5 block text-xs leading-5 text-[var(--ledger-text-muted)]">{detail}</span></span><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} className="mt-0.5 h-4 w-4 accent-[var(--ledger-accent)]" /></label>;
export const LoadingRow = ({ label, detail, action }: { label: string; detail?: string; action?: ReactNode }) => <div className="flex items-start gap-3"><Loader2 size={16} className="mt-0.5 animate-spin text-[var(--ledger-accent)]" aria-hidden="true" /><div className="min-w-0 flex-1"><p className="text-[13px] font-medium" role="status" aria-live="polite">{label}</p>{detail && <p className="mt-1 text-xs text-[var(--ledger-text-muted)]">{detail}</p>}{action && <div className="mt-3 flex gap-2">{action}</div>}</div></div>;
