import { AlertCircle, Check, ExternalLink, Folder, Loader2, Plus, RefreshCw, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useApi } from '../../hooks/useApi';
import { GoogleDriveIcon } from '../Common/GoogleDriveIcon';
import { useToast } from '../Common/ToastProvider';
import { IntegrationSection, MetaRow, settingsIntegrationButton, settingsIntegrationPrimary } from './FigmaIntegrationPage';
import { ExternalProviderOperationStatus, type ExternalProviderOperation } from '../Projects/ExternalProviderOperationStatus';

type Status = { status?: string; provider_account_email?: string | null; connected_at?: string | null; updated_at?: string | null; last_error?: string | null };
type Source = { id: string; name: string; provider_source_id?: string; canonical_url?: string | null; status?: string; last_successful_refresh_at?: string | null; external_metadata?: Record<string, unknown>; relationship?: { project?: { id: string; name: string } | null; connected_by?: { full_name?: string | null; email?: string | null } | null } | null };
type Template = { id: string; name: string; description?: string | null; structure?: { folders?: Array<{ name: string; children?: Array<{ name: string }> }> }; updated_at?: string | null };
type Rule = { id: string; name: string; trigger_type?: string; actions?: Array<{ type?: string }>; enabled?: boolean; last_error?: string | null; last_success_at?: string | null };

const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '—';
const openExternal = (url?: string | null) => { if (!url) return; if (window.desktopWindow?.openExternal) void window.desktopWindow.openExternal(url); else window.open(url, '_blank', 'noopener,noreferrer'); };
const openOAuth = async (api: ReturnType<typeof useApi>) => { const result = await api.connectGoogleDrive() as { url?: string }; if (!result.url) throw new Error('Google Drive authorization is unavailable.'); if (window.desktopWindow?.openExternal) await window.desktopWindow.openExternal(result.url); else window.open(result.url, '_blank', 'noopener,noreferrer'); };

export function GoogleDriveIntegrationPage({ workspaceId, canManage, onBack, onStatusChange }: { workspaceId: string | null; canManage: boolean; onBack: () => void; onStatusChange?: (status: Status) => void }) {
  const api = useApi(); const toast = useToast();
  const [status, setStatus] = useState<Status>({ status: 'disconnected' }); const [sources, setSources] = useState<Source[]>([]); const [monitoring, setMonitoring] = useState<any>(null); const [templates, setTemplates] = useState<Template[]>([]); const [rules, setRules] = useState<Rule[]>([]); const [operations, setOperations] = useState<ExternalProviderOperation[]>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null); const [confirmDisconnect, setConfirmDisconnect] = useState(false); const [editingTemplate, setEditingTemplate] = useState<Template | 'new' | null>(null); const [templateName, setTemplateName] = useState(''); const [templateStructure, setTemplateStructure] = useState('{\n  "folders": []\n}');
  const refresh = async () => { if (!workspaceId) return; setLoading(true); try { const [nextStatus, nextSources, nextMonitoring, nextTemplates, nextOperations] = await Promise.all([api.getGoogleDriveIntegrationStatus(), api.getGoogleDriveConnectedSources(), api.getGoogleDriveMonitoring(), api.getExternalFolderTemplates(), api.getGoogleDriveOperations()]); const normalized = nextStatus as Status; setStatus(normalized); onStatusChange?.(normalized); setSources(Array.isArray(nextSources) ? nextSources as Source[] : []); setMonitoring(nextMonitoring); setTemplates(Array.isArray(nextTemplates) ? nextTemplates as Template[] : []); setOperations(Array.isArray(nextOperations) ? nextOperations as ExternalProviderOperation[] : []); const sourceRows = Array.isArray(nextSources) ? nextSources as Source[] : []; const ruleRows = (await Promise.all(sourceRows.map((source) => api.getConnectedSourceRules(source.id).catch(() => [])))).flat(); setRules(ruleRows as Rule[]); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not load Google Drive settings.', { variant: 'error' }); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, [workspaceId]);
  const connected = status.status === 'connected'; const statusLabel = status.status === 'connected' ? 'Connected' : status.status === 'revoked' ? 'Reconnect required' : status.status === 'error' ? 'Needs attention' : 'Not connected';
  const beginOAuth = async (label: string) => { setBusy(label); try { await openOAuth(api); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not open Google authorization.', { variant: 'error' }); } finally { setBusy(null); } };
  const disconnect = async () => { setBusy('disconnect'); try { await api.disconnectGoogleDrive(); setConfirmDisconnect(false); await refresh(); toast.show('Google Drive disconnected.', { variant: 'success' }); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not disconnect Google Drive.', { variant: 'error' }); } finally { setBusy(null); } };
  const saveTemplate = async () => { let structure: unknown; try { structure = JSON.parse(templateStructure); } catch { toast.show('Use valid folder structure JSON.', { variant: 'error' }); return; } setBusy('template'); try { if (editingTemplate === 'new') await api.createExternalFolderTemplate({ name: templateName.trim(), structure }); else if (editingTemplate) await api.updateExternalFolderTemplate(editingTemplate.id, { name: templateName.trim(), structure }); setEditingTemplate(null); await refresh(); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not save template.', { variant: 'error' }); } finally { setBusy(null); } };
  const openTemplateEditor = (template: Template | 'new') => { setEditingTemplate(template); setTemplateName(template === 'new' ? '' : template.name); setTemplateStructure(JSON.stringify(template === 'new' ? { folders: [] } : template.structure || { folders: [] }, null, 2)); };
  const applyTemplate = async (template: Template) => { const source = sources.find((item) => item.relationship?.project?.id && item.provider_source_id); if (!source?.relationship?.project?.id || !source.provider_source_id) { toast.show('Connect a Google Drive folder to a project before applying a template.', { variant: 'error' }); return; } setBusy('apply-template'); try { const result = await api.createGoogleDriveProjectStructure(source.relationship.project.id, { template_id: template.id, destination_folder_id: source.provider_source_id, root_name: source.relationship.project.name, idempotency_key: `template-settings:${source.relationship.project.id}:${template.id}` }) as { operation?: ExternalProviderOperation }; if (result.operation) setOperations((current) => [result.operation as ExternalProviderOperation, ...current.filter((item) => item.id !== result.operation?.id)]); toast.show('Folder structure creation started.', { variant: 'success' }); } catch (error) { toast.show(error instanceof Error ? error.message : 'Could not apply folder template.', { variant: 'error' }); } finally { setBusy(null); } };
  const templatePreview = (template: Template) => (template.structure?.folders || []).map((folder) => folder.name).join(' · ') || 'Empty structure';
  const monitoringLabel = monitoring?.status === 'active' ? 'Active' : monitoring?.status === 'disabled' ? 'Disabled' : monitoring?.status === 'connection_required' ? 'Reconnect required' : 'Delayed';
  const sourceCount = sources.length;
  return <section className="w-full max-w-215" aria-labelledby="settings-google-drive">
    <button type="button" onClick={onBack} className="mb-5 inline-flex items-center gap-1 text-xs font-medium text-[var(--ledger-text-muted)] hover:text-[var(--ledger-text-primary)]">← Integrations</button>
    <div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[var(--ledger-surface-muted)]"><GoogleDriveIcon size={20} /></span><div><h2 id="settings-google-drive" className="text-2xl font-semibold tracking-tight text-[var(--ledger-text-primary)]">Google Drive</h2><p className="mt-1 text-[13px] leading-5 text-[var(--ledger-text-secondary)]">Connect Google Drive files, folders, and activity to your Ledger work.</p></div></div>
    {!canManage && <p className="mt-5 flex items-center gap-2 text-xs text-[var(--ledger-danger)]"><AlertCircle size={14} />You don’t have permission to manage Google Drive integration settings.</p>}
    <IntegrationSection title="Connection">{loading ? <LoadingRow label="Checking Google Drive connection…" /> : !connected ? <div className="flex items-center justify-between gap-4"><div><p className="text-[13px] font-medium">Connect Google Drive</p><p className="mt-1 text-xs text-[var(--ledger-text-muted)]">Browse and link Google Drive files to your Ledger projects and work.</p></div><button type="button" className={settingsIntegrationPrimary} disabled={!canManage || !!busy} onClick={() => void beginOAuth('connect')}>{busy === 'connect' ? 'Opening…' : 'Connect Google Drive'}</button></div> : <><div className="divide-y divide-[color:var(--ledger-border-subtle)]"><MetaRow label="Connected account" value={status.provider_account_email || 'Google account'} /><MetaRow label="Status" value={statusLabel} icon={<Check size={14} />} /><MetaRow label="Connected on" value={formatDate(status.connected_at)} /><MetaRow label="Last checked" value={formatDate(status.updated_at)} /></div>{status.status !== 'connected' && <p className="mt-3 text-xs text-amber-900">{status.last_error || 'Reconnect Google Drive to resume live access.'}</p>}<div className="mt-4 flex gap-2"><button type="button" className={settingsIntegrationButton} disabled={!canManage || !!busy} onClick={() => void beginOAuth('reconnect')}>{busy === 'reconnect' ? 'Opening…' : 'Reconnect'}</button><button type="button" className={settingsIntegrationButton} disabled={!canManage || !!busy} onClick={() => void beginOAuth('switch')}>{busy === 'switch' ? 'Opening…' : 'Switch account'}</button></div></>}</IntegrationSection>
    <IntegrationSection title="Connected folders">{sources.length === 0 ? <div className="py-2"><p className="text-[13px] font-medium">No connected folders</p><p className="mt-1 text-xs text-[var(--ledger-text-muted)]">Connect a Google Drive folder from a Ledger project to manage its files and activity here.</p></div> : <div className="divide-y divide-[color:var(--ledger-border-subtle)]">{sources.map((source) => <div key={source.id} className="flex items-center gap-3 py-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[var(--ledger-surface-muted)]"><Folder size={15} className="text-[var(--ledger-text-muted)]" /></span><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium">{source.name}</p><p className="mt-0.5 truncate text-xs text-[var(--ledger-text-muted)]">{source.relationship?.project?.name || 'Ledger project'} · {source.status === 'active' ? 'Active' : source.status || 'Needs attention'} · {Number(source.external_metadata?.itemCount || 0)} items</p><p className="mt-0.5 text-[11px] text-[var(--ledger-text-muted)]">Connected by {source.relationship?.connected_by?.full_name || source.relationship?.connected_by?.email || 'Ledger user'} · Refreshed {formatDate(source.last_successful_refresh_at)}</p></div><button type="button" className="rounded-md p-1.5 text-[var(--ledger-text-muted)] hover:bg-[var(--ledger-surface-hover)]" title="Open in Google Drive" onClick={() => openExternal(source.canonical_url)}><ExternalLink size={14} /></button>{source.relationship?.project?.id && <button type="button" className={settingsIntegrationButton} onClick={() => window.history.pushState({}, '', `/?window=module&module=projects&project=${encodeURIComponent(source.relationship!.project!.id)}`)}>Open project</button>}</div>)}</div>}</IntegrationSection>
    <IntegrationSection title="Monitoring"><div className="divide-y divide-[color:var(--ledger-border-subtle)]"><MetaRow label="Status" value={monitoringLabel} icon={monitoring?.status === 'active' ? <Check size={14} /> : undefined} /><MetaRow label="Last successful check" value={formatDate(monitoring?.state?.last_successful_drain_at)} /><MetaRow label="Monitored folders" value={String(sourceCount)} /></div>{monitoring?.status !== 'active' && canManage ? <button type="button" className={`${settingsIntegrationButton} mt-3`} disabled={!!busy} onClick={() => void (setBusy('monitoring'), api.repairGoogleDriveMonitoring().then(refresh).catch((error) => toast.show(error instanceof Error ? error.message : 'Could not repair monitoring.', { variant: 'error' })).finally(() => setBusy(null)))}>{busy === 'monitoring' ? 'Retrying…' : 'Retry monitoring'}</button> : null}</IntegrationSection>
    <IntegrationSection title="Rules">{rules.length ? <div className="divide-y divide-[color:var(--ledger-border-subtle)]">{rules.map((rule) => <div key={rule.id} className="flex items-center gap-3 py-2.5"><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium">{rule.name}</p><p className="mt-0.5 text-xs text-[var(--ledger-text-muted)]">{rule.trigger_type || 'Drive change'} · {(rule.actions || []).map((action) => action.type?.replace(/_/g, ' ')).filter(Boolean).join(', ') || 'No actions'}</p></div><span className="text-[11px] text-[var(--ledger-text-muted)]">{rule.enabled ? 'Enabled' : 'Disabled'}</span></div>)}</div> : <p className="text-xs text-[var(--ledger-text-muted)]">No Google Drive rules configured.</p>}</IntegrationSection>
    <IntegrationSection title="Folder templates"><div className="flex items-center justify-between gap-3"><p className="text-xs text-[var(--ledger-text-muted)]">Reusable folder structures for project work.</p>{canManage && <button type="button" className={settingsIntegrationButton} onClick={() => openTemplateEditor('new')}><Plus size={13} className="mr-1 inline" />Create template</button>}</div>{templates.length ? <div className="mt-3 divide-y divide-[color:var(--ledger-border-subtle)]">{templates.map((template) => <div key={template.id} className="flex items-center gap-3 py-2.5"><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium">{template.name}</p><p className="mt-0.5 truncate text-xs text-[var(--ledger-text-muted)]">{templatePreview(template)}</p><p className="mt-0.5 text-[11px] text-[var(--ledger-text-muted)]">Updated {formatDate(template.updated_at)}</p></div>{canManage && <><button type="button" className={settingsIntegrationButton} onClick={() => openTemplateEditor(template)} title="Edit"><RefreshCw size={13} className="mr-1 inline" />Edit</button><button type="button" className={settingsIntegrationButton} disabled={busy === 'apply-template'} onClick={() => void applyTemplate(template)}>Apply to project</button><button type="button" className="rounded-md p-1.5 text-[var(--ledger-danger)] hover:bg-[color:rgba(217,45,32,0.08)]" onClick={() => { if (window.confirm(`Delete ${template.name}?`)) void api.deleteExternalFolderTemplate(template.id).then(refresh); }} title="Delete"><Trash2 size={13} /></button></>}</div>)}</div> : null}</IntegrationSection>
    {operations.length ? <IntegrationSection title="Recent operations"><div className="space-y-2">{operations.map((operation) => <ExternalProviderOperationStatus key={operation.id} operation={operation} />)}</div></IntegrationSection> : null}
    <IntegrationSection title="Danger zone"><div className="flex items-start justify-between gap-4"><div><p className="text-[13px] font-medium">Disconnect Google Drive</p><p className="mt-1 max-w-xl text-xs leading-5 text-[var(--ledger-text-muted)]">Ledger will stop accessing this Google account. Existing linked resources, folder connections, Intake records, and cached metadata will remain in Ledger, but live updates and Drive actions will stop until an account is reconnected.</p></div><button type="button" className="shrink-0 rounded-full border border-[color:rgba(217,45,32,0.18)] px-3 py-2 text-xs font-medium text-[var(--ledger-danger)] hover:bg-[color:rgba(217,45,32,0.08)]" disabled={!canManage || !!busy} onClick={() => setConfirmDisconnect(true)}>Disconnect Google Drive</button></div></IntegrationSection>
    {editingTemplate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 p-6"><div className="w-full max-w-lg rounded-2xl border border-[color:var(--ledger-border-subtle)] bg-[var(--ledger-surface-card)] p-5 shadow-[var(--ledger-shadow)]"><h3 className="text-base font-semibold">{editingTemplate === 'new' ? 'Create template' : 'Edit template'}</h3><label className="mt-4 block text-xs font-medium">Template name<input value={templateName} onChange={(event) => setTemplateName(event.target.value)} className="mt-1 h-9 w-full rounded-md border border-[color:var(--ledger-border-subtle)] bg-transparent px-2 text-sm" /></label><label className="mt-3 block text-xs font-medium">Folder structure<textarea value={templateStructure} onChange={(event) => setTemplateStructure(event.target.value)} rows={8} className="mt-1 w-full rounded-md border border-[color:var(--ledger-border-subtle)] bg-transparent p-2 font-mono text-xs" /></label><div className="mt-4 flex justify-end gap-2"><button type="button" className={settingsIntegrationButton} onClick={() => setEditingTemplate(null)}>Cancel</button><button type="button" className={settingsIntegrationPrimary} disabled={!templateName.trim() || busy === 'template'} onClick={() => void saveTemplate()}>{busy === 'template' ? 'Saving…' : 'Save template'}</button></div></div></div>}
    {confirmDisconnect && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 p-6"><div className="w-full max-w-sm rounded-2xl border border-[color:var(--ledger-border-subtle)] bg-[var(--ledger-surface-card)] p-5 shadow-[var(--ledger-shadow)]"><h3 className="text-base font-semibold">Disconnect Google Drive?</h3><p className="mt-2 text-sm leading-5 text-[var(--ledger-text-secondary)]">This does not delete Google Drive files or Ledger resources. It stops metadata refresh, monitoring, and Drive write actions, and connected folders may need reconnection later.</p><div className="mt-5 flex justify-end gap-2"><button type="button" className={settingsIntegrationButton} onClick={() => setConfirmDisconnect(false)}>Cancel</button><button type="button" className="rounded-full bg-[var(--ledger-danger)] px-3 py-2 text-xs font-medium text-white" disabled={busy === 'disconnect'} onClick={() => void disconnect()}>{busy === 'disconnect' ? 'Disconnecting…' : 'Disconnect Google Drive'}</button></div></div></div>}
  </section>;
}

const LoadingRow = ({ label }: { label: string }) => <div className="flex items-center gap-2 py-2 text-xs text-[var(--ledger-text-muted)]"><Loader2 size={14} className="animate-spin" />{label}</div>;
